### ISSUE TITLE
MonsterBlocks

### ISSUE THREAD

**Issue by west1778** [Aedif/TokenVariants#10]
When using the newly *Added a right-click listener to the Actor Sheet portrait to bring up the module's Art Select screen.* from version 1.5.1 it doesn't appear to open the Art Select Screen instead it pops up the image browser. Not sure if it's a MonsterBlock issue or if something can be done from this end. Figured I'd start here though.

**Comment by Aedif** [comment]
Hi,

I installed MonsterBlock but couldn't replicate the issue. 

Would you mind opening up the actor sheet, pressing F12 to get into console and then Ctrl+Shift+C and hove over the portrait?

You should see something like this:

![image](https://user-images.githubusercontent.com/7693704/119721094-a50b8480-be62-11eb-8c2e-7a92e492ac70.png)

It'd be useful to know if it's still identified as 'img.profile'.

**Comment by Aedif** [comment]
I believe I found the issue. 

I assume you're using MonsterBlock's actor sheet with image enabled?

Unfortunately I don't believe there to be an easy way for the **Token Variant Art** Right-click to overwrite the Right-click behaviour of MonsterBlock. The best I can do is make the Art Select screen appear together with the image browser.

**Comment by west1778** [comment]
Ah yeah, I am. Ok didn't know if it was an error or something. Thank you for replying. I can use TidyNPC and it works fine there thanks a ton and an awesome module too by the way. :)
