### ISSUE TITLE
Active effects Aplly Filter without changing the image?

### ISSUE THREAD

**Issue by jacksands** [Aedif/TokenVariants#100]
Tks for the incredible module! use and recommend it all the time!

I'm probably just not knowing how to do it in the settings, but it is possible to only apply one filter on a Active Effects?

I'm trying to config Token Magic FX on some Status, but it apply on a "symbol" over the token... it is possible to apply it on the token image directly? I was able to define a Image for changing. but I wish for an effect that can be apply on any token and with any image...

How can I do it?

Right now it is like this...

![filter 1](https://user-images.githubusercontent.com/7229143/223514833-d295f6a9-d978-4ec1-8c9a-30107f3bc77d.png)

![filter 2](https://user-images.githubusercontent.com/7229143/223514848-88a898ab-0e00-4ac1-a7c7-b784dee44535.png)

**Comment by Aedif** [comment]
![image](https://user-images.githubusercontent.com/7693704/223519319-9d7471e0-d8cb-4a49-9df3-d82ec090ab39.png)
This is how you apply a TMFX preset to the token itself.

**Comment by Aedif** [comment]
You can also directly paste macros into the `Run on Apply` and `Run on Remove` fields:
![image](https://user-images.githubusercontent.com/7693704/223520545-47836c35-a00f-4e52-8010-e75f68af758c.png)

**Comment by jacksands** [comment]
TKS!!!  worked Flawlessly!!
