### ISSUE TITLE
Client settings affecting all players

### ISSUE THREAD

**Issue by AFigureOfBlue** [Aedif/TokenVariants#101]
Hi- I'm using this module on Foundry v10 with the Pathfinder 2nd Edition system in order to give one of my players the ability to change out their PC's token art on the fly. Since only one player needs to use this, I'd ideally like to not have the Token HUD Button displayed for all players, but when I log in as a player and go to configure the Token HUD Client Settings, the changes I make seem to be made for all players... so, if I hide the button for one player, it hides it for all of them, rather than being saved on a per-player/client basis. It would be great to be able to set this so that the extra button isn't shown to players who won't be needing it.

**Comment by Aedif** [comment]
Should be fixed in 4.31.1

**Comment by AFigureOfBlue** [comment]
Thanks for the quick reply! But I just upgraded the module and tested this out again, and the bug seems to still be present. If I log in as one player, adjust the Token HUD Client Settings, then go and log in as another player, the changes made from the first player seem to also be applying to the second.

**Comment by Aedif** [comment]
There was a problem with GM settings overwriting the player settings in some specific scnearios, but what you're experiencing is actually this:
![image](https://user-images.githubusercontent.com/7693704/224495607-f6efa8d7-02fc-4bf6-af69-9d323cbd03b7.png)

Your users need to set thse settings themselves.

**Comment by Aedif** [comment]
To prevent your users from seeing art you don't want them to you can do this for their tokens:
![image](https://user-images.githubusercontent.com/7693704/224496074-1464e8cf-16f4-45f6-94ac-21fd1168cc55.png)

Then if they don't want to see the buttons they can just disable it via the client settings.

**Comment by AFigureOfBlue** [comment]
Ah, I see. That's a bummer, as I was hoping to help keep the interface simple for my players without them needing to do any extra settings adjustments, but it sounds like that's related to how settings are configured, unrelated to this module. Thank you for the information!
