### ISSUE TITLE
Question about the token HUD button

### ISSUE THREAD

**Issue by Nedrapter** [Aedif/TokenVariants#102]
My players have loaded their tokens in Forge Library Assets and set the path.
On left clicking on the HUD button shows only the current token, like this
![image](https://user-images.githubusercontent.com/74311190/226208538-ded6fc93-ad7a-42d4-a6a1-b684e649241f.png)
But if they right click and search the icons, they do appear in a grid.
![image](https://user-images.githubusercontent.com/74311190/226208573-3ae15a0a-eabc-4ac6-b5e1-61517f97bcda.png)

Is that normal? I thought they left click should be showing all tokens they have in that folder?

**Comment by Aedif** [comment]
The module searches using the token's name and places the found images in that grid.

Are you telling me that these images do not show up when your players click on the button, but do when they right-click it and perform the search using the token's name manually? Or are they performing different searches?

**Comment by Nedrapter** [comment]
> 

Those tokens do not show when they left click on the button. Only the one used shows (as shown in 1st image). They only show up if they are searched.

**Comment by Aedif** [comment]
I'm testing it right now and it works for me.
Can you tell me what the token name is, and what they type into the search?

**Comment by Nedrapter** [comment]
They type "icon" since all of them are named Icon + something else e.g. "Icon Crow" to have them all show up. Could it be some wrong configuration on my/their part?

**Comment by Nedrapter** [comment]
We're trying with a test token currently, so the name is just some nonsense, like this 
![image](https://user-images.githubusercontent.com/74311190/226214495-4a314e2a-2c89-419c-a452-fe5fc4064167.png)
Why does the token name matter though?

**Comment by Aedif** [comment]
By default the Token HUD only includes images that the module could find using the token's name. If for example your players Token is named "Alexander" the module will perform the search using "Alexander" and only return the images that match it.

What I assume is happening is that yoiur players token name does not match any of those images, but they do match the search "icon".

**Comment by Nedrapter** [comment]
Ah I see. I did not know it has to match. Does it have to match 100%? Meaning all variant tokens have to be the exact same name?

**Comment by Nedrapter** [comment]
Okay so I changed 3-4 of them to match the token's name. Now 1 of them appears, but not the rest.
![image](https://user-images.githubusercontent.com/74311190/226214668-4fbeb24a-de79-4e90-a312-3fd1cb784ebb.png)
What could be happening now?

**Comment by Aedif** [comment]
Depends on the search algorithm you're using. The fuzzy algorith does not require exact matches.

I'd suggest that your players place their images in a folder named after their character and then you'll need to enable the `Match name to folder` setting.

![image](https://user-images.githubusercontent.com/7693704/226214618-7f30a50a-4793-4c5a-893b-97df21c619ee.png)

**Comment by Nedrapter** [comment]
Thanks, now it works properly! So many settings to be aware of ... :D
