### ISSUE TITLE
Turn On AE Crashes the Canvas

### ISSUE THREAD

**Issue by brunocalado** [Aedif/TokenVariants#104]
Hi.

I create this AE with these settings and it crashes the canvas.
![image](https://user-images.githubusercontent.com/4999783/229378929-1cefd03a-32c3-4de9-bd78-00dd695a4d67.png)

![image](https://user-images.githubusercontent.com/4999783/229378944-acd6bf7f-12ae-4d2e-889f-c3242b0c8699.png)

https://user-images.githubusercontent.com/4999783/229378864-e0dfcab9-7777-4354-b8c2-3a681c2d6c27.mp4

tks

**Comment by Aedif** [comment]
Should be fixed in release https://github.com/Aedif/TokenVariants/releases/tag/4.33.2

**Comment by brunocalado** [comment]
tks
