### ISSUE TITLE
Overlay z-index issue

### ISSUE THREAD

**Issue by this-gavagai** [Aedif/TokenVariants#105]
Thanks so much for this incredible module! I'm still slowly learning all of the various features, but it has added so much polish to my games.

I've noticed one small issue: If there are multiple tokens in a square, a text overlay will layer above all of them, not just the token it is attached to. Is there any way in the settings to force overlays to the same z-index range as their tokens?

https://user-images.githubusercontent.com/9303694/230131936-18c8337f-9bf6-497a-a2f2-5a6cee515cd8.mp4

If there's anything I can do to explain further or better, please let me know. Thanks again! This module is absolutely fantastic.

**Comment by Aedif** [comment]
Should be fixed in release [4.34.0](https://github.com/Aedif/TokenVariants/releases/tag/4.34.0)

Also added a couple of new optionst to retain this behavious when needed.

**Comment by this-gavagai** [comment]
Fabulous! I'm trying to test it out but foundry keeps trying to download 4.33.2. I'm not sure if it's a manifest issue or a problem on my side. I'll poke into it when I get access to my server later today.

Thanks again! This module is so great.

**Comment by Aedif** [comment]
Yes, there was an issue with the manifest. Should be alright now.
