### ISSUE TITLE
image configuration doesn't work (in swade system?)

### ISSUE THREAD

**Issue by bloy** [Aedif/TokenVariants#106]
Foundry Version: 10.291
SWADE system version: 2.2.5
Token Variant Art version: 4.34.1

Expected behavior:
shift + leftclick on HUD image choice brings up token config with selection checkboxes, to configure that image

Actual behavior:
shift + leftclick on HUD image brings up token config, without checkboxes. Changes are not applied to token config
console message: TypeError: tokenConfig is undefined (from `modules/token-variants/applications/tokenCustomConfig.js:104`) 

suspected cause: line 103 of `tokenCustomConfig.js` is not finding anything useful in `this.config` or in `getTokenConfig`, so 104 is throwing the TypeError.

**Comment by Aedif** [comment]
Should be fixed in 4.34.2
