### ISSUE TITLE
Tint Color don't work

### ISSUE THREAD

**Issue by brunocalado** [Aedif/TokenVariants#107]
Hi.

I can't get the tint color to work. Any tips?

![image](https://user-images.githubusercontent.com/4999783/230798838-d0a50485-d822-42c6-b02c-eb2448433740.png)

**Comment by Aedif** [comment]
That text is black.. Tinting works the same way as it does on tokens. 

Black will not take on any tint, it's like trying to stain a pitch black kettle. 

If you want tint to have any effect at all you need to set that text to some other color, preferably white.
