### ISSUE TITLE
Forge Bazaar search paths

### ISSUE THREAD

**Issue by pinkflumph** [Aedif/TokenVariants#109]
I'm trying to add the Forgotten Adventures bazaar assets to the search paths and for some reason the core folder is never getting cached. 

Specifically, the paths to FA assets are all of the following form: "...bazaar/assets/FA_", e.g. "...bazaar/assets/FA_Adversaries_Bandits_01/Bandits/Bandit_Archer_01.webp". After adding a forge-bazaar source with the path "assets/FA_Adversaries_Bandits_01" the module properly caches all the images under "FA_Adversaries_Bandits_01" and its nested folders. However, given a forge-bazaar source with just "assets" as its path, the module doesn't cache or find any of the images. I've tried getting around this by adding a source with "assets/FA_*" as the path, but that hasn't helped:

![image](https://github.com/Aedif/TokenVariants/assets/99619418/f618ab54-dd02-4182-ba74-1856d6c82ba8)

Is there any way to fix this? I'd rather avoid adding each one of the folders manually (and adding a new one every time a new package is published). Thanks!

**Comment by Aedif** [comment]
Seems like some sort of restriction enforced by ForgeVTT.

I implemented a workaround in the latest release: https://github.com/Aedif/TokenVariants/releases/tag/4.38.0

**Comment by pinkflumph** [comment]
Just tested, it works. Amazing, thanks!
