### ISSUE TITLE
Excluded keywords for token/portrait art

### ISSUE THREAD

**Issue by PBobovsky** [Aedif/TokenVariants#11]
It would be neat if the excluded keywords were on individual art type basis.
Currently if I have portrait art containing the word portrait, I cannot limit the token art to not offer it without also preventing portrait art to offer it.

**Comment by Aedif** [comment]
New 'Search Filter Settings' have been added that expand on the filtering options.

Portrait, Token and General (Portrait+Token) searches can now be individually configured with pieces of text that must either be included or excluded in the file names. Alternatively a regular expression can be added for more complex cases.

Available in release 1.7.0
