### ISSUE TITLE
[Feature Request] Comparators for HP Gain/Loss to Effect Config

### ISSUE THREAD

**Issue by harrisog** [Aedif/TokenVariants#115]
It would be great to be able to trigger changes simply based on whether HP has been gained or lost. I may be wrong but I don't think this is doable currently. Perhaps something like `hp\++` and `hp\--` as special operators?

**Comment by Aedif** [comment]
What are you intending to use this for?

**Comment by Aedif** [comment]
Asking since HP being reduced or increased is an 'event' which I assume you want to last only for a certain amount of time. 

At the moment the module only deals with 'enduring' states such as token properties and Active Effects which last until they are changed again.

**Comment by harrisog** [comment]
For my particular use case, I am just running a sequencer script on apply. I am finding that TVA's UI lets me do things with sequencer that Automated Animations is not set up for (in particular with the logical operators and comparators). With the requested feature, I am hoping to set up simple scripts to play sound file "snarls" when an enemy is hit (&& \! Dead && \! Paralyzed, etc.).

An extension of the requested feature that is more in line with the module's core purpose would be to allow temporarily changing token arts to a "wince" state when hit, and/or "soothed" state when healed. This could possibly extend further into overlays to show temporary floating Adam West Batman-style text ("Pow!", "Biff!" etc.). Admittedly, both of these ideas would probably just be better handled via an on apply sequencer script like my use case, but again, this is nowhere near doable with Automated Animations.

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/4.43.0

New setting added under `Active Effects > `Internal Effects` > `HP Change`
