### ISSUE TITLE
[Bug] Effect Config Input of Composite Expressions with Multiple Strings 

### ISSUE THREAD

**Issue by harrisog** [Aedif/TokenVariants#117]
When typing composite expressions with more than one component wrapped in string quotes into the Effect Config, inputting the second character of the second string causes the text selector to unexpectedly move to the beginning of the input field.

Example: `lockRotation="true" && name="Raging Barbarian"`

Copy-pasting in from elsewhere seems to bypass, but any attempt to further edit the expression inside the Effect Config will result in the bug.

**Comment by harrisog** [comment]
I'm encountering a related bug with composite expressions and quotes with the TMFX preset. Example: `Dazzled && \{ name="Orc Brute" || name="Orc Warrior" || name="Orc Warchief"\}`

The preset works as expected for the first match in the array, but does not automatically delete itself for any matches in later array positions.

And piggybacking off this example with a QoL feature request: please consider extending wildcard searches to name strings? E.g., `Dazzled && name="Orc \*"

**Comment by Aedif** [comment]
For that king of expression you need to use parentheses () not curly brackets {}

**Comment by Aedif** [comment]
Curcly brackets are purely used for matching a string to some effect name akin to how you would use them in Token Image Wildcards (https://foundryvtt.com/article/tokens/). I intentionally made syntax the same.

For logical expression you want to use the parentheses. Think of each part of the expression as being ture or false and translate it as so:

```Dazzled && \( name="Orc Brute" || name="Orc Warrior" || name="Orc Warchief" \)```

```true && (false || false || true)```

If what you end up with can be pasted into your browser console and evaluates without error, you have a valid expression.

**Comment by Aedif** [comment]
If instead of `Dazzled` you used `Dazzled \{1,2,3\}` The module would evaluate the whole of `Dazzled \{1,2,3\}` as either true or false depending on whether the token has a dazzled effect with the name `Dazzled 1`, `Dazzled 2`, or `Dazzled 3`, and this would be plugged back into the logical expression:

```Dazzled \{1,2,3\} && \( name="Orc Brute" || name="Orc Warrior" || name="Orc Warchief" \)```

```true && (false || false || true)```

**Comment by harrisog** [comment]
Gotcha, everything's working as expected then. Thanks again!
