### ISSUE TITLE
Feature Request: Support for Expressions/Variables in More Fields

### ISSUE THREAD

**Issue by Dumbhuman** [Aedif/TokenVariants#118]
I'd never really played around with Effect Mapping before, but seeing the latest release video inspired me.  I was very happy to be able to use the torus and a couple of expressions...
![image](https://github.com/Aedif/TokenVariants/assets/63615591/500bc426-509f-46c9-a0b0-4e0375826e96)

...to make a quick Spirit Guardians aura that correctly scales with token size, always extending just 15 feet from the token's space.
![image](https://github.com/Aedif/TokenVariants/assets/63615591/90cf33c6-5482-4178-9fdb-6369575b7e6e)

That's fantastic, but unfortunately without expressions support in the Appearance field, I can't use artwork to get the same effect of a 15' radius that stays 15' as the token's size changes.  If I unlink it from the token scale, then the artwork stays the same size as the token gets bigger (so the Large token below effectively gets a 12.5' aura):
![image](https://github.com/Aedif/TokenVariants/assets/63615591/539a2239-2052-497a-b750-9723ce91ef6c)

If I link it to the token scale, then the aura will be proportionate to the token's size and either too big for a Large one is I set it up for a Medium one or too small for a Medium token if I set it for a Large one (as below):
![image](https://github.com/Aedif/TokenVariants/assets/63615591/2ffe6e6f-7ead-4579-98bf-dad7da3f0fe4)

I'm guessing that currently one could make a bunch of effects for each size category and have each one only apply if the token is of that size, but that means any desired future edits to such effects would need to happen in a lot of different places.  It would be very nice if expressions/variables could be used in the Appearance tab to make edits easier.

Another place I'd love to be able to use expressions/variables is in the Text tab.  I was able to use expressions and variables to make a decent little spell slot tracker that updates automatically as spells are used and which itself can scale well with token size.  When I attempted to add some labels to it, the text scaling understandably didn't do so well.
![image](https://github.com/Aedif/TokenVariants/assets/63615591/3ef2b4ca-ebe6-4ead-a1b5-b2f61eca6971)

Maybe you've already thought about including this stuff or maybe it's complicated enough to make you not want to tackle it, but I figured I'd mention it as a feature request just in case.  You're doing great work (and the reward for that is almost always people asking you to do more of it)!

**Comment by Aedif** [comment]
Hmm, interesting uses for overlays. 👍  I'd be curious to see how the finished spell slot tracker works.

I guess what you're really after here is the ability to directly specify width and height under the appearance tab; independent of the various scaling options that the module provides. (Under the hood `Text` is actually an image too so this setting would affect it as well)

I'll play around with this tomorrow.

Btw you can share your mappings/overlay by exporting them via the Mappings form header button.

**Comment by Dumbhuman** [comment]
I wouldn't exactly call this finished, but it's as far as I got while playing around with it earlier:

[token-variants-spell_slot_tracker_test.zip](https://github.com/Aedif/TokenVariants/files/12246630/token-variants-spell_slot_tracker_test.zip)

Ironically (given this request ticket), I could've used a lot more variables than I did to make future edits easier.  I'll probably do a bit of find/replace in Notepad++ to rectify that at some point.

Luckily your video gave me the syntax I needed to reference the spell slot attributes.  Ideally I'd also like to include an expression that evaluates whether the actor even has spell slots, but I didn't dive into figuring out how to do that yet.

**Comment by Aedif** [comment]
Love the spell slot wheel.

I'll extend expression support to all values that can currently only be set via sliders + add `Width` and `Height`  fields to the `Appearance` tab which will let you bypass scaling and let you directly specify image/text dimensions.

All of these changes have already been implemented but I'll need a bit more time to test.

**Comment by Dumbhuman** [comment]
That sounds great and thank you very much for the quick addition!  Looks like you've got a new Foundry update to test with too so I guess it timed well with another verified compatibility bump.
