### ISSUE TITLE
Option to skip the "Use same art for token" dialogue

### ISSUE THREAD

**Issue by PBobovsky** [Aedif/TokenVariants#12]
It's just a single click, but it would speed up the process by 33% :P

**Comment by Aedif** [comment]
Hello,

If you want the same art to be applied both to the portrait in the actor sheet as well as the token this can already be done without the intermediate dialogue if you disable the '<b>Display separate pop-ups for Portrait and Token art</b>' setting.

**Comment by PBobovsky** [comment]
No that's not the issue :) 

I have that option enabled because I want different arts for token and portrait. 
What I'd like is an option to get rid of this prompt (and instantly take me to the "choose token art" prompt)
![image](https://user-images.githubusercontent.com/24353249/121680476-e5e9d700-cab9-11eb-8d39-49fddd006dce.png)

**Comment by Aedif** [comment]
A new setting has been added 'Disable prompt between Portrait and Token art select'

Available in release 1.7.0
