### ISSUE TITLE
Text wrapping not supported

### ISSUE THREAD

**Issue by kevinb0** [Aedif/TokenVariants#122]
In the text field, it'd be neat to be able to enable word wrapping, or something to attempt to fit the text within a certain size. 

I'm trying to read through a character's appearance, and it's not possible to make it cleanly fit into a box.  It'd be neat if you could toggle on some sort of word rap, or limit to write it so it doesn't overflow. 

![image](https://github.com/Aedif/TokenVariants/assets/23584271/c8eb1eeb-9bf4-41f0-a5a8-de1f63b0e71d)

**Comment by Aedif** [comment]
A simple word wrap based on some number of pixels should be very easy. I might experiment with wrapping to the parent as well. We'll see how it goes.

**Comment by Aedif** [comment]
Text wrapping options added in release 4.49.0
