### ISSUE TITLE
Global Effects Not Firing and Configuration Window not Opening

### ISSUE THREAD

**Issue by Drowbe** [Aedif/TokenVariants#123]
After updating to 4.49.2, two things are happening:

1.  I had a global effect configured to display a "dead" image when an NPC hit 0 hp... it is no longer firing. It worked in the last version.
2.  Upon trying to investigate why the effect is not firing, I found that when I clicked "Settings > Token Varient Art > Settings > Active Effects > Global Effects Configuration > Configure" the "configure" window doesn't open up.  I have restarted the server, disabled and enabled the module, but the configure window still does not open. Any changes I make in the other tabs seem to work.

I have tried to do this on both Windows and Mac, two different browsers.

BTW, Thanks for an awesome module!

**Comment by Drowbe** [comment]
![Screenshot 2023-08-16 at 11 32 58 AM](https://github.com/Aedif/TokenVariants/assets/140648353/c355228f-b1e3-43d3-9063-057d6164d0a6)

Cleaned the console log and simply pressed the "configure" button.

**Comment by Drowbe** [comment]
Sorry --- should have expanded the log:

![image](https://github.com/Aedif/TokenVariants/assets/140648353/4537863a-eb03-4bed-b9fb-e775034ce05d)

**Comment by Aedif** [comment]
It's probably the same issue as this one:
https://github.com/Aedif/TokenVariants/issues/121

Follow the steps in there to resolve it. I'll see to fixing this bug asap

**Comment by Drowbe** [comment]
Yeah... that fixed getting into the config. It also fixed the custom effect not firing. Apologies for opening a dupe, I cruised the issues but didn't notice the details of that one! I will close this.
