### ISSUE TITLE
FEATURE REQUEST: Exclude from Token Variant Art checkbox in Prototype Token Menu

### ISSUE THREAD

**Issue by DeviousHearts** [Aedif/TokenVariants#124]
A simple checkbox in the Prototype Token menu to EXCLUDE an actor from using Token Variant Art. Simple and effective for those stuck in one unique form but still leaving all the functionality to others.

**Comment by Aedif** [comment]
New options added: https://github.com/Aedif/TokenVariants/releases/tag/4.50.0
