### ISSUE TITLE
Overlay: Text Aligment isn't saving, always defaulting to "Left";

### ISSUE THREAD

**Issue by Vargock** [Aedif/TokenVariants#125]
While working on some overlay effects, I've noticed that "Text Alignment" just... doesn't save xD Tried doing this on a new world, but the issue remained. It seems to always default to "Left" state;
![изображение](https://github.com/Aedif/TokenVariants/assets/93734306/b28ac596-9269-4137-8c76-f4554ca7a91a)

**Comment by Aedif** [comment]
It is actually being saved, but upon re-opening the form the select box is not being set to the correct value.

Will fix in the next release. For now simply make sure that you select desired alignment before you `Apply` the changes.

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/4.51.0
