### ISSUE TITLE
[Suggestion] Heart, squares life as count.

### ISSUE THREAD

**Issue by atleticano-snp** [Aedif/TokenVariants#126]
First, thanks for the module. The features are amazing.

I would like to suggest that the implantation of hearts and other symbols like % of life could be configured as remaining amount.

Example: A character with 6 life (20 maximum), would show 6 symbols, not 3 (30%).
Motivation: systems with small values would make it easier to see the rest of the selected attribute.

**Comment by Aedif** [comment]
This can already be done my changing the `Repeating` section of thos templates:

For example, change this:

![image](https://github.com/Aedif/TokenVariants/assets/7693704/7dd3fd8c-b857-4723-b0a5-bce1ac53f52f)


to this:
![image](https://github.com/Aedif/TokenVariants/assets/7693704/0bf113db-4f31-443e-80d0-e5736198d518)
