### ISSUE TITLE
No expression for hidden state?

### ISSUE THREAD

**Issue by kevinb0** [Aedif/TokenVariants#127]
This may be a user error issue, but I don't think it's possible to have active text show/hide based on the hidden status of an entity?

For example, this bear is hidden 
![image](https://github.com/Aedif/TokenVariants/assets/23584271/b27889ae-300a-4e40-88e9-511472207d82)
It'd be nice if there was an expression to only show the active effects if the entity isn't hidden. This isn't an issue for players, only for the GM.

**Comment by Aedif** [comment]
`hidden="false"`

![image](https://github.com/Aedif/TokenVariants/assets/7693704/acf01fe4-5373-4a21-a080-5f2929593788)

The origin of these expressions is `_token.document`, any property it has is accessible in the expression field
