### ISSUE TITLE
[Feature Requests] Have "Image Names Contain Dimensions" be case-insensitive and work with percentages (i.e. "_ScaleXXX_")

### ISSUE THREAD

**Issue by morepurplemorebetter** [Aedif/TokenVariants#129]
The "Image Names Contain Dimensions" setting is amazing, thank you for making something I didn't know I dearly needed!

It would be nice if the "_scaleX_" part of the name wasn't case-sensitive and scale could be expressed as a percentage. If you do that, this module would be instantly compatible with the naming convention used by [Forgotten Adventures](https://www.forgotten-adventures.net/product-category/tokens/), whose free tokens are used by the D&D 5e system SRD monsters.

**Comment by Aedif** [comment]
I'd need exact details about the format used by FA. What does the percentage mean in this case? Does it map 1:1 with token scale in Foundry? If percentage is bellow 100, how is it represented? With leading zeroes or no?

**Comment by morepurplemorebetter** [comment]
Some example filenames:

- Dragonborn_Barbarian_Spear_Scale300_01
- Adult_Blue_Dragon_Huge_Scale233_Dragon_01
- Allosaurus_Large_Scale200_Beast_01
- Hill_Giant_Huge_Scale166_Giant_01

There don't seem to be any tokens with scale below 100%, as they have white margins to make the token smaller.

The biggest scale seems to be 300%

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/4.52.0

**Comment by morepurplemorebetter** [comment]
Awesome!
