### ISSUE TITLE
Can't find the settings for this module in my "module settings"

### ISSUE THREAD

**Issue by Avitale34** [Aedif/TokenVariants#13]
Hello I am new to this module and am trying to set it to look in a specific directory for assets, I can't seem to find any setting in the configure settings for this module. How are you suppose to change it?

**Comment by Aedif** [comment]
There should be a setting called 'Variant art search paths':

![image](https://user-images.githubusercontent.com/7693704/121741074-e7d18b80-caf5-11eb-880a-0d95bb8f76d1.png)

Clicking on the button will open up a window as so:

![image](https://user-images.githubusercontent.com/7693704/121741139-fe77e280-caf5-11eb-9b04-38e137508b17.png)

**Comment by Avitale34** [comment]
Hmm I can't even find it as an option I am using the forge.
![image](https://user-images.githubusercontent.com/65961637/121742978-99f55d00-cace-11eb-9870-c13c193764d9.png)
![image](https://user-images.githubusercontent.com/65961637/121743464-65ce6c00-cacf-11eb-8e10-cda6de45521d.png)

**Comment by Aedif** [comment]
Do you see any errors in the console? (F12>Console)

Also the module initializes itself when the scene is rendered. Are you checking the module setting after opening a scene?

**Comment by Avitale34** [comment]
That was it, I was using a brand new game and had no active scenes yet.

**Comment by Aedif** [comment]
Adding a comment for the record: 

Module initializes on game **ready** now. Rendering a scene should no longer be necessary for the module to register settings.
