### ISSUE TITLE
[Feature Requests] Set dimensions back to default when changing from file with '_scaleX_' to without

### ISSUE THREAD

**Issue by morepurplemorebetter** [Aedif/TokenVariants#130]
The "Image Names Contain Dimensions" setting is amazing, thank you for making something I didn't know I dearly needed!

Currently, when I select a file that has "scale1.5" as part of the name, the token gets scaled to 1.5 times.
If I then change the token again, but this time to a file that doesn't include any "scaleX", the previous scale of 1.5 stays. It would be really great if the token would instead reverts back to the default scale set for the actor's prototype token.

**Comment by Aedif** [comment]
The module already does that, as long as the image changes are being made through it.

**Comment by morepurplemorebetter** [comment]
Apologies, seems it did work after a cache refresh and a reload.
