### ISSUE TITLE
"Overlay" settings for "Active Effects" aren't being saved

### ISSUE THREAD

**Issue by Vargock** [Aedif/TokenVariants#131]
https://github.com/Aedif/TokenVariants/assets/93734306/fa9482f5-632c-41f6-9057-0cac7f828733

**Foundry VTT:** Version 11 Stable (307)
**Module:** version 4.51.0
**Issue**: changes to "Overlay" settings for "Active Effects" aren't being saved. The video example was filmed with other modules enabled, but I tested it without any after the fact and the issue still persisted. I've first noticed that settings sometimes didn't save a few updates ago, but it seems that now they don't save at all;

**Comment by Aedif** [comment]
It seems like this is an issue onyl when accessing global mappings via the Configure Settings. I'll look into it but for now use the shortcut key:

![image](https://github.com/Aedif/TokenVariants/assets/7693704/8ad5e9f7-a284-49db-8b88-3390be53c912)

**Comment by Aedif** [comment]
You can also access global via the header menu of the actor one. Have a look at the form's header buttons.

**Comment by Vargock** [comment]
Not related to an issue, but may I inquire either or not it's possible to use actor's JS element values as Width/Height/Variable in the "Overlay" settings? For example, to set "Width" to "prototypeToken.width"? Or something similar to this.

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/4.52.0

All text fields within overlay forms support JS code, and `token` is accessible through them.

`token.actor.prototypeToken.width * 100` is a valid expression
![image](https://github.com/Aedif/TokenVariants/assets/7693704/758d36d4-e254-4eb4-8107-b9d0f034f139)
