### ISSUE TITLE
[Bug] "Randomize Wildcard Images" checkbox in Prototype Token dialog is malfunctioning

### ISSUE THREAD

**Issue by morepurplemorebetter** [Aedif/TokenVariants#132]
The checkbox is not being set properly. It seems to be checked by default, while no wildcard is in the Image Path. And when I do add a wildcard to the Image Path, I have to unset the checkbox, save, and then check the box again for the wildcard to work. But when I open the Prototype Token dialog after that, the checkbox is unchecked.

Tested on:

- FoundryVTT v11.307
- D&D 5e v2.3.0
- Token Variant Art v4.52.0

in a test world with only TVA active (and libWrapper).

**Comment by Aedif** [comment]
Should be fixed in : https://github.com/Aedif/TokenVariants/releases/tag/4.52.1
