### ISSUE TITLE
[Feature Suggestion] In "Global Effects", add an ability to use executable custom JS code in the "Expression" box, 

### ISSUE THREAD

**Issue by Vargock** [Aedif/TokenVariants#133]
![image](https://github.com/Aedif/TokenVariants/assets/93734306/5c2a06b1-82b3-4b2a-8f7b-2be1a2129ec1)
_As promised, writing this a feature suggestion over here._

As of now, TVA does not execute any code within the expression, but it would be nice to have an option of doing so — for example, changing the current way the expression is evaluated for some custom executable JS code.

**Comment by Aedif** [comment]
Feel free to give it a whirl: https://github.com/Aedif/TokenVariants/releases/tag/4.53.0

**Comment by Vargock** [comment]
> Feel free to give it a whirl: https://github.com/Aedif/TokenVariants/releases/tag/4.53.0

That was fast 😮 Thank you so much! I've checked it on that case that I've asked about in discord, and all seems to work well!
