### ISSUE TITLE
Does this work with PF2e Effects?

### ISSUE THREAD

**Issue by this-gavagai** [Aedif/TokenVariants#136]
Hello, thanks for this great module.

I've used Token Variants to good effect with hp conditions.

I'm trying to understand if it works for effects in the pf2e system. Simply put, when an actor/token has an effect with the name "Effect: Hybrid Shape (Beastkin)", I want to display a different token. I've not been able to get it to work. Am I doing something wrong, or is this not a feature of the module?

(I've tried every matching pattern I can think of, with or without quotes, with or without `name=`, with or without slashes, etc.)

**Comment by Aedif** [comment]
It should work but perhaps I broke it when I made some changes to the module. I will fix it in the next release.

fyi these are the item types that the module should be picking up:

`'condition', 'effect', 'weapon', 'equipment'`

**Comment by Aedif** [comment]
PF2e effects should once again work within mapping expressions: https://github.com/Aedif/TokenVariants/releases/tag/4.53.1

**Comment by this-gavagai** [comment]
Wow, I am so appreciative of how responsive you've been. My 10yo son is very, very excited to play a Werebeaver, and the ability to toggle his token when the effect kicks in is just so cool. It's working great.
