### ISSUE TITLE
[bug] "malformed URI sequence" error for filenames with a percent sign (%) in them

### ISSUE THREAD

**Issue by morepurplemorebetter** [Aedif/TokenVariants#137]
I agree, percent signs (%) in URI are a bad idea, but some 3rd-party asset creator didn't think of that and it took me a while to figure out exactly which file was the culprit, as it was causing the whole caching to fail.

The issue is with the `getFileName` function [here in utils.js](https://github.com/Aedif/TokenVariants/blob/master/scripts/utils.js#L533-L536).

[Known workarounds for this issue](https://stackoverflow.com/questions/7449588/why-does-decodeuricomponent-lock-up-my-browser) are not great. I think adding a `try { ... } catch (err) { ... }` might be the best way to go and add a warning message on error (or just to the console).

**Comment by Aedif** [comment]
A console warning will now be thrown if such an image is detected instead of crashing out of caching.

https://github.com/Aedif/TokenVariants/releases/tag/4.54.0
