### ISSUE TITLE
Token Mold Name Override Prevents Token Variant Art Randomiser / Popups from working

### ISSUE THREAD

**Issue by schmickers** [Aedif/TokenVariants#139]
When the modules Token Mold and Token Variant art are active, the token image randomizer and image select pop ups from Token Variant Art do not occur. 

Disabling the Name setting in the Token Mold header restores this functionality. 

**To Reproduce**
1. Install Token Mold
2. Install token Variant Art
3. Create a token
4. Token image is not randomised by TVA

**Expected behavior**
Token Mold should make its changes to the token name and allow TVA to randomise the image / display an art select pop-up. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Foundry Virtual Tabletop: Version 11 Stable, 11.308
 - Game System: dnd5e, 2.3.1
 - token Mold 2.20.3
 - Token Variant Art 4.56.1

**Comment by schmickers** [comment]
I have discovered that also using the core options in V11 for prepending or appending names to new tokens also causes the randomiser not to work.

**Comment by Aedif** [comment]
Since when does core append anything to the token names? 🤔 What's the setting that does this?

**Comment by Aedif** [comment]
Found the setting and randomization seems to work just fine, same goes for the pop-ups.

I think you might be confused perhaps by needing to adjust the `Percentage Match` to be lower

![image](https://github.com/Aedif/TokenVariants/assets/7693704/e50fbc2a-bf2f-4362-9040-47a4ae946b45)

And the fact that randomization overrides Pop-ups. If you disable randomizaiton you should see pop-ups again.

**Comment by Aedif** [comment]
With a token selected press `Shift + 2`, you'll see that no images are found with 70% match. Lower it and the images will show up again
