### ISSUE TITLE
[Feature Suggestion] add the ability to use executable custom JS code in text in overlay

### ISSUE THREAD

**Issue by LeandroMartinelli** [Aedif/TokenVariants#145]
Hi, first of all, great work and thanks for the incredible module!

My suggestion came from the fact than when we use the text overlay only some simple variable or text cam be used, but the possibility to make some JS code for simple calculations would bee great!
Examples: 

- 'Distance between tokens' {{_token.distanceTo(token)}} 
- 'XP to next level' {{xp.max - xp.value}}

Thank you for the attention

**Comment by Aedif** [comment]
Code can already be entered into that field. Simply make sure that the value returned in a string.

e.g.

```js
const xp = token.actor.system.details.xp;
xp.max - xp.value + ""
```

**Comment by LeandroMartinelli** [comment]
Thanks I'm using it wrong then!!
```JS
{const xp = token.actor.system.details.xp;
"XP: " + (xp.max - xp.value) + "" }}
```
Works just fine, but I'm using in a way how return 0 everytime
```JS
XP: {{token.actor.system.details.xp.max - token.actor.system.details.xp.value}}
```
Again, thanks for the great work!

**Comment by Aedif** [comment]
Thanks for the template submitions 👍. I've made a couple of adjustments and have approved them.
