### ISSUE TITLE
option to search by folder name/compatibility with token images imported from roll20

### ISSUE THREAD

**Issue by MrPotatoZed** [Aedif/TokenVariants#15]
I was hoping this would be the perfect way to deal with porting several hundred token images from roll20 to foundry actors. Unfortunately, roll20 strikes again as after import to foundry the token portraits and avatar filenames are all "token.png" and "avatar.png". The distinguishable keywords are in the folder names. Is there any way to allow for searching folder names in addition to filenames (i.e. attributing the folder name text to the files inside)? If searching folder names generally would cause too many problems what about allowing users to designate a few particular folders to be searched by the folder name?

**Comment by Aedif** [comment]
Hello,

Just to confirm, what you're seeking here is something like this:

Search: **Dragon**
Matches:
* token_art/monsters/**dragon**/token.png
* caeora/random_tokens/**dragon**_60x60.png
* **dragon**s/red/avatar.png
  
If so then this shouldn't be too difficult to implement.

**Comment by Aedif** [comment]
This has been implemented in release **1.10.0**.

A new setting has been added '**Match name to folder**' which when enabled will check the names against folders as well as the files.

Check it out and see if this meets your needs. 👍

**Comment by MrPotatoZed** [comment]
It works beautifully, thank you! I was concerned turning this on might lead to a lot of unrelated "false positives" but so long as people are aware of/avoid using the keywords in their variant art search paths it isn't an issue.
