### ISSUE TITLE
Bizarre issue with Custom Config Token Variant not working with "{ }" file paths

### ISSUE THREAD

**Issue by Foundry37** [Aedif/TokenVariants#151]
Hello,

So I use a folder called "{Spirits}" to keep some of my token art in (for spirit versions of the normal FA tokens), but for some reason while I can Shift-Left-Click in the Token HUD selection to have normal tokens enact a custom config for things like scale or opacity, when I try to use any token from the "{Spirits}" folder it refuses to display any custom changes to it.

**To Reproduce**
1. Name a folder "{Spirits}" - likely just the {}'s are the issue.
2. Stick some normal tokens that accept custom config changes in there.
3. Open the Token HUD selection for variants.
4. Shift-Left-Click the variant that's in a folder called "{Spirits}" and try to add any change to it.
5. Observe that it doesn't seem to display any of those changes no matter how you refresh or click on and off with another token variant.
6. Rename the "{Spirits}" folder to just "Spirits" without the brackets.
7. Now doing a custom config change on that token variant should work just fine.

**Expected behavior**
I have no idea why the {}'s in a file path for a variant token art would stop something so specific from occurring.

**Screenshots**
![TVA Issue](https://github.com/Aedif/TokenVariants/assets/99896703/23d7f92b-98b3-4c7f-b29d-c64142271eeb)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome - but I use the VTT.exe for this and DM-ing.
 - Mod Version: 4.64.1

**Additional context**
Honestly lucky I managed to figure out vaguely why this is happening, it confused me a great deal. While for now it's easy to just rename my folders with a {} in them, I'm confused why it's happening in the first place.

**Comment by Aedif** [comment]
Should be fixed in [4.64.2](https://github.com/Aedif/TokenVariants/releases/tag/4.64.2)
