### ISSUE TITLE
Compendium Mapper not changing proto token image when there already is something assigned

### ISSUE THREAD

**Issue by Juppstein** [Aedif/TokenVariants#153]
**Describe the bug**

I made a copy of an actor (monster) compendium ( Old School Essential Advanced Fantasy Rules Tome) and wanted to change the portrait and proto token images with the Token Variant Compendium Mapper.  The portraits seem to change just fine but the prototype tokens don't change. The actors already have a dummy proto token image preset by default. When I clear out the image path the mapper works and the correct image is applied, so if there is something in the image path field the mapper won't touch/change it. Is there a setting in the compendium mapper to force update an entry?

**To Reproduce**
1. Go to '...Comendium Mapper'
2. Configure Mapper to assign images to prototype token
3. Click Start
4. Go through a set of actors to change the token art
5. When you go to the actor's token settings the art has not been applied when there already was an image assigned to it before

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS 
 - Browser: Chrome
 - Version  122.0.6261.57 

**Additional context**
Foundry server running on Ubuntu 22.04 LTS Server (headless), self hosted.

**Comment by Aedif** [comment]
Should be fixed in [4.64.2](https://github.com/Aedif/TokenVariants/releases/tag/4.64.2)

**Comment by Juppstein** [comment]
Yup, works as intended now 👍🏽
