### ISSUE TITLE
Fonts Added to Core System

### ISSUE THREAD

**Issue by blackdiamond923** [Aedif/TokenVariants#157]
**Is your feature request related to a problem? Please describe.**
Not really a problem per say but I would like to use a few of the fonts I've added to the system on the overlays and at the moment it doesn't seem to pick those up.

**Describe the solution you'd like**
I would like to see the fonts I've added be useable in the overlays. 

I appreciate you and your modules!

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/5.0.5
