### ISSUE TITLE
Module no longer works in v12

### ISSUE THREAD

**Issue by Stevesonio** [Aedif/TokenVariants#158]
The icon for changin token art no longer appears
And yes. The module is active.
Tried reinstalling it - nothing
![image](https://github.com/Aedif/TokenVariants/assets/171579155/e9de2b96-fb2a-4d29-9de2-53e0166c73e5)

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/5.0.0
