### ISSUE TITLE
Error on trying to display actor type selection on global effects mapping

### ISSUE THREAD

**Issue by brother-oak** [Aedif/TokenVariants#159]
Just installed this module, so am new to setting stuff up.
Have set up some global effects mappings, which work fine, but when I click on the "actor type" button for any of my mappings, in order to select only NPCs, no popup window is displayed, and the following error is shown in the debug console:

effectMappingForm.js:707 Uncaught TypeError: n is not iterable
    at EffectMappingForm._onConfigureApplicableActors (effectMappingForm.js:707:21)
    at HTMLDivElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

This is running in the FVTT native app, version 12.327
Using DnD 5e system, version 3.2.1
Module version 5.0.1
(all latest as of 26th June 2024)

**Comment by Aedif** [comment]
Should be fixed in https://github.com/Aedif/TokenVariants/releases/tag/5.0.2

**Comment by brother-oak** [comment]
Perfect. Works for me now :-) Many thanks
(Not sure if you want me to close this, or if you prefer to have control over closing the issues)
