### ISSUE TITLE
Searching asset library on forge?

### ISSUE THREAD

**Issue by Avitale34** [Aedif/TokenVariants#16]
As the heading states I am having trouble getting my asset library to be recognized in the search. Is it possible to refer to your asset library? Edit: got it to work :)

**Comment by Aedif** [comment]
Sorry for the late reply. Glad you found the way to do it. 👍 

This is not the first time this has been asked so I updated the README with the ForgeVTT example: 

https://assets.forge-vtt.com/{userId}/path/to/token/art
