### ISSUE TITLE
[Bug] "Display Token Effect Icons on Hover" Nonfunctional

### ISSUE THREAD

**Issue by megahead11** [Aedif/TokenVariants#160]
DND 3.2.1
Foundry v12.328
Chrome

The option for "Display Token Effect Icons on Hover" doesn't appear to function properly. When enabled, the statuses are shown all the time, instead of on hover. Additionally, sometimes it WILL work, with the icons being hidden, but once you hover over them, they show until you refresh.

**Comment by Aedif** [comment]
Should be fixed in 5.0.4
