### ISSUE TITLE
Can't read expression

### ISSUE THREAD

**Issue by Vaganarch** [Aedif/TokenVariants#162]
when there is number in the property, the expression cant seem to work at all. is there a way to fix this?
![image](https://github.com/user-attachments/assets/b6d25cfb-0fb8-47a9-b069-dcb1802b696d)
![image](https://github.com/user-attachments/assets/95ce2554-a7ff-46cf-9d06-7842df7d5fe4)

**Comment by Aedif** [comment]
Should be fixed in 5.0.4
