### ISSUE TITLE
[Feature Suggestion] Hide Overlays in darkness or not fully rendered.

### ISSUE THREAD

**Issue by Ikabodo** [Aedif/TokenVariants#166]
**Is your feature request related to a problem? Please describe.**
Newer versions of foundry, especially with modules like Vision 5e, has a wide range of vision modes. Several of them are intended to "hide" what the character sees. They can see that "someone" is there, but not exactly what. Problem arises that if you have overlays, they display no matter what. So that might easily give away who it is.

**Describe the solution you'd like**
Add an option to hide overlays based on if they are not in vision.

![image](https://github.com/user-attachments/assets/26bf83a5-5fd8-4ffa-9f9b-30d49e11e628)
Example of a situation where an overlay should not be visible if possible.

**Comment by Aedif** [comment]
Overlays are not shown when the token is out of vision range. 

Every core vision mode as far as I'm aware will reveal the look of the token and all UI elements surrounding it such as the nameplate.

What you want is just speciic integration with Vision 5e which has the ability to only show the approximate position of a token and nothing else?

**Comment by Ikabodo** [comment]
Ah, I think I understand now. Then yes, this seems like more of an integration issue between the mods than anything.

What I think would be nice if there is a toggle to respect Vision 5e's vision modes. If the vision mode doesn't show the token. The overlay with this checkbox should also not show.

But I fully understand that this might be out of scope. Thanks for taking a look at it!
