### ISSUE TITLE
Suggestion: Always Show Token HUD Button

### ISSUE THREAD

**Issue by cameron-dyson** [Aedif/TokenVariants#17]
Currently the token HUD button is only displayed if matching art is found. It would be nice if the button was always displayed so that the right click to search option was always available.

For example, currently if I have a token named "villager" but only have art for it containing the name "commoner", then the token HUD button will not be displayed:

![image](https://user-images.githubusercontent.com/77019706/123456056-0761bd00-d5a8-11eb-97f2-2dfdbceac46a.png)

 If instead it was always displayed and allowed for the right click to search, I could use this to search for the "commoner" art 
and assign it to the "villager" token like this:

![image](https://user-images.githubusercontent.com/77019706/123456378-64f60980-d5a8-11eb-8967-5b36a7218411.png)

**Comment by Aedif** [comment]
Added a new setting under 'Token HUD Settings'  : **Always show HUD Button**

Is available in release 1.11.0

**Comment by cameron-dyson** [comment]
Thanks, works great.
