### ISSUE TITLE
Compendium Mapper does not launch

### ISSUE THREAD

**Issue by Truncated** [Aedif/TokenVariants#170]
**Describe the bug**
Compendium Mapper does not open.

**To Reproduce**

1. Open Configure Game Settings
2. Open Token Variant Art Compendium Mapper (gears button)
3. Set any setting options; I've tried a lot of combos with the same results. 
4. Click Start at the bottom.
5. Nothing happens - console logs following message after a second or two. If I set the cache to refresh, it will give the message that it finished that action before throwing the error below.
```
pf2e.mjs:1580 
 Uncaught (in promise) 
TypeError: undefined. Cannot read properties of undefined (reading 'type')
[Detected 2 packages: system:pf2e(6.2.2), token-variants(5.1.1)]
    at Proxy.getDefaultArtwork (pf2e.mjs:1580:210817)
    at FilePathField.initial (foundry-esm.js:14716:38)
    at f (compendiumMap.js:333:77)
    at Array.map (<anonymous>)
    at CompendiumMapConfig.startMapping (compendiumMap.js:439:31)
```
﻿
**Expected behavior**
The compendium mapper interface should open and begin allowing me to apply new icons based on the search options.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Edge Version 127.0.2651.105 (Official build) (64-bit)
 - Version - Core Version: 12.331

System: pf2e 6.2.2 (The PF2e System Developers) 

Modules: 
lib-wrapper 1.12.15.0 (Rui Pinheiro)
module-credits 2.2.3 (Mouse0270)
socketlib 1.1.0 (Manuel Vögele)
token-variants 5.1.1 (Aedif)

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/5.1.2
