### ISSUE TITLE
Overlay config error when Convenient Effects is enabled

### ISSUE THREAD

**Issue by Opius134** [Aedif/TokenVariants#171]
When Dfred's Convenient Effects is enabled, Token Variants errors out when opening the overlay configuration cog. 

![image](https://github.com/user-attachments/assets/bff3ff52-3f85-4ff4-9f9f-ca60d5f617ce)

![image](https://github.com/user-attachments/assets/5a1576c7-aaba-4dfa-9574-23b687103654)

it's possible the OverlayConfig.js script is referencing the old version of Convenient Effects, as the module has been completely rewritten. I've attempted to omit parts of the code as a hacky workaround with no luck. 

Modules: Dfred's Convenient Effects 7.0.1, TokenVariants 5.1.1
Environment: Foundry Virtual Tabletop: Version 12 Stable, 12.331
Game System: dnd5e, 3.3.1

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/5.1.2
