### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by VladGrant** [Aedif/TokenVariants#2]
The newest update stopped working with the following error:

Uncaught (in promise) TypeError: path.startsWith is not a function
    at token-variants.mjs:133
    at Array.forEach (<anonymous>)
    at getSearchPaths (token-variants.mjs:132)
    at findTokens (token-variants.mjs:186)
    at displayArtSelect (token-variants.mjs:285)
    at replaceTokenConfigImage (token-variants.mjs:243)
    at HTMLButtonElement.el.onclick (token-variants.mjs:118)
(anonymous) @ token-variants.mjs:133
getSearchPaths @ token-variants.mjs:132
findTokens @ token-variants.mjs:186
displayArtSelect @ token-variants.mjs:285
replaceTokenConfigImage @ token-variants.mjs:243
el.onclick @ token-variants.mjs:118
async function (async)
displayArtSelect @ token-variants.mjs:285
replaceTokenConfigImage @ token-variants.mjs:243
el.onclick @ token-variants.mjs:118

This also happens when it's the only module enabled.

**Comment by Aedif** [comment]
Should be fixed now with release 1.3.1

If not try to update 'Variant art search paths' in the module settings. That should fix it as well.
