### ISSUE TITLE
Feature Request - Accept as options a list of web url structured in a specific json

### ISSUE THREAD

**Issue by p4535992** [Aedif/TokenVariants#23]
Accept as options a list of web url (and file) structured in a specific json instead of a path to a folder.

The idea is to save as much space as possible by using web urls instead of images in folders.

In my case the images are reachable as url in different sites to use the tool I should download them in the appropriate folders or use something like s3 .

Here a example of what i have mind:

```json
  { 
    "Goblin" : 
    [
      {
       "name": "Goblin1",
       "keys": ["goblin", "green"],
       "type": "actor",
       "icon": "https://i.imgur.com/9r84Vmk.png"
     },
     {
       "name": "Goblin2",
       "keys": ["goblin", "green", "leader"],
       "type": "actor",
       "icon": "https://i.imgur.com/6r84Vmk.png"
     },
    ],
    "Guards" : 
    [
      {
       "name": "Guard01",
       "keys": ["guard"],
       "type": "actor",
       "icon": "/systems/dnd5e/icons/actor/xxx.jpg"
     },
     {
       "name": "Guard2",
       "keys": ["guard", "captain"],
       "type": "actor",
       "icon": "https://i.imgur.com/5r84Vmk.png"
     },
    ],
}
```

If you like the idea, but you don't want to integrate it because you are busy with something else, I would like to try it myself, but after I have agreed with you on how to set it up programmatically.

**Comment by Aedif** [comment]
Hey,
Your pull has been implemented in release 1.13.1
I fixed a couple bugs and made a few touch ups like supporting multiple names under the same path which is now possible due to rolltables being used as an image source.
