### ISSUE TITLE
suggestion: store scale settings per token image

### ISSUE THREAD

**Issue by dirusulixes** [Aedif/TokenVariants#24]
I understand this probably is outside of the scope of the module, but here is my suggestion: a way to store information about the scale the token image should use per token image. 

The use case is a character token having a 'social' token and a 'in-combat' token. The latter has a more dynamic pose and needs to be scaled up to, let's say, 1.2 not to look too small. The module could set the scale automatically based on the information provided beforehand once the picture is chosen. It would default to 1 if no information is provided.

**Comment by Aedif** [comment]
Hello, sorry for responding so late.

Ability to add custom configuration has now been introduced as of release 1.15.1

To assign a custom configuration shift+left-click on the image in either the **Art Select** window or the **Token HUD** side menu:

![image](https://user-images.githubusercontent.com/7693704/145683772-6493f0e7-564e-477c-8730-b863e9a6fb50.png)

Once configured this way swapping to such as image using the **Token Variant Art** module will auto-apply this configuration to the token.
