### ISSUE TITLE
Disable for PC ?

### ISSUE THREAD

**Issue by CaosFR** [Aedif/TokenVariants#26]
Hi,

First, congratulaty for your usefull module.

Is there a way to disable Token Variants PC or enable only for NPC ?
Maybe based on the caracter sheet ?

Thanks

**Comment by Aedif** [comment]
Hello,

Would you like to disable ALL of the module features by PC/NPC types or just specific ones? For example even if pop-ups are disabled for PC tokens would you still want to have the extra button in the Token HUD?

**Comment by CaosFR** [comment]
Thanks for your reply. I think just disable the pop-ups is enough beceause it's create a error (F12) if there are no other picture for the PC. The button will not create any problem and I think and can be usefull.

**Comment by Aedif** [comment]
Hello, sorry for the massive delay... 

As of release 1.16.1 the module pop-ups can now be disabled for specific Actor types (PC/NPC/Vehicle) through the **Pop-up Settings**:

![image](https://user-images.githubusercontent.com/7693704/145833965-e7b261ee-a5a5-4241-8072-1be05f5614f8.png)

**Comment by CaosFR** [comment]
Very good, thanks.
