### ISSUE TITLE
[Suggestion] Option to hide popup window from players

### ISSUE THREAD

**Issue by jameswmills** [Aedif/TokenVariants#3]
First off, I want to thank you for this module.  It makes developing encounters so much more fun and dynamic!

I use rolltables to dynamically generate encounters, and the monsters I use in the rolltable are from a compendium.  So, when I drag them on to the scene, this module pops up and I can choose the variant I want for each particular monster (which is awesome).  Unfortunately, it also pops up for all the players, and they get confused :-)

Is there any chance you could add an option to hide the popup from the players?

Thanks!

**Comment by Aedif** [comment]
Hello James,

Glad you're enjoying the module : )

Pop-up showing up for the players was unintended. This should now be fixed and no longer happening in release 1.3.2
