### ISSUE TITLE
Expose more functions for use in Macros

### ISSUE THREAD

**Issue by crimsonknave** [Aedif/TokenVariants#31]
:wave: I've been loving this so far, but I was wondering if you could expose a few more functions on `game.TokenVariants` for use in macros? My use case is a bit outside of the main scope of the addon, but, I have a macro that generates some information about an NPC and puts it in chat. I was hoping to be able to add a randomly chosen token to include in the chat window as well just like I get when I drag a token from the actor list. So, I was looking at the `doRandomSearch` and if you added that it would make sense to add the search functions as well I think.

**Comment by Aedif** [comment]
Hi,

I'll give it some though and see what I can do. Will likely need to cleanup and refactor some of the code before I expose anything...

**Comment by Aedif** [comment]
Hi,

**doArtSearch(...) and doRandomSearch(...) and now exposed through **game.TokenVariants** as of release 1.17.1

https://github.com/Aedif/TokenVariants#api
