### ISSUE TITLE
Ability to disable randomization for some, but not all NPCs

### ISSUE THREAD

**Issue by crimsonknave** [Aedif/TokenVariants#32]
Maybe I'm missing something, but I haven't found a way to have an NPC not get a randomized token. I don't want my named NPCs getting a random image, but I do want my guards to. I believe that I've seen some other addons only apply to actors that have a prototype token that isn't linked, which would be ideal. Otherwise, a setting for the actor somewhere that disabled the randomization would be great.

**Comment by Aedif** [comment]
Hello,

More settings have been added to the randomizer as of release **1.16.1**. In hindsight I should have really included these when I first added the feature but I guess better late than never...

![image](https://user-images.githubusercontent.com/7693704/145834433-f06c6a5d-619c-4d45-b906-c5ab8f6f2477.png)
