### ISSUE TITLE
Disable for Token Creation but Enabled for Actor Creation

### ISSUE THREAD

**Issue by friction1** [Aedif/TokenVariants#33]
I can't seem to find a way to configure the settings so that the popup occurs once when I create an actor, but then never again when I drag the actor onto the scene to make a token or when I copy and paste tokens on the board. 

Thanks!

**Comment by Aedif** [comment]
Hi,

More options have been added to the 'Pop-up Settings' as of release 1.17.1:

![image](https://user-images.githubusercontent.com/7693704/146227278-1f8a2297-5785-405e-82e3-6e2d06b4aa3c.png)

**Comment by friction1** [comment]
Thanks so much!
