### ISSUE TITLE
Can't change Portrait image with Token HUD button

### ISSUE THREAD

**Issue by AetherianRPG** [Aedif/TokenVariants#34]
When using Token HUD button to change token art, character portrait does not change. Don't know if this is a bug or intentional, just reporting. If this is working as intended, I would like to suggest an option to change both of them at the same time when using Token HUD button. Thanks.

**Comment by Aedif** [comment]
Hey,

This was intended but seeing as there is no reason not to allow this I added a new setting to let you do this:

![image](https://user-images.githubusercontent.com/7693704/146354018-e1456f05-1047-4ee7-8729-805ac4c0ff72.png)

Available in **Release 1.18.1**
