### ISSUE TITLE
Can't find pictures, even in a dedicated folder

### ISSUE THREAD

**Issue by Yashael** [Aedif/TokenVariants#39]
This add-on sounds very interesting, but search engine can't find any of my pictures, even if the path to the tokens folder is indicated in settings. Is that because my data folder is in a USB drive? Or did I miss something about a setting?

**Comment by Aedif** [comment]
Hello,
Are you able to access these images through the image browser?:

![image](https://user-images.githubusercontent.com/7693704/151411440-9bb250de-9723-4752-9232-64045528a7ee.png)

As long as you can; pasting the path that you can see at the top into the '**Search Paths**' setting should work:

![image](https://user-images.githubusercontent.com/7693704/151411641-ab81904f-b5f1-4043-a103-ba0fbc477d23.png)

If you can't access these images through the '**Image Browser**' you'll need to **link** these images to you data folder. If you're on windows this can be done through the command promp by running the command: 

mklink/D path/to/your/foundry/data/folder path/to/your/usb/folder

e.g.
![image](https://user-images.githubusercontent.com/7693704/151413101-427c299f-cdb8-4bf3-a891-fd7c15202910.png)

**Comment by Yashael** [comment]
It works better! Thank you!
