### ISSUE TITLE
Suggestion: Have a window pop up with the an editable field for the search string.

### ISSUE THREAD

**Issue by Sunamon** [Aedif/TokenVariants#4]
when you click the button for an actor with a unique name it will not find a picture. but if the window that popped had a dynamic search box you could edit... So instead of getting nothing for my "Bilbo Baggings" actor I can edit the "Bilbo baggings" text and refresh the search with the new name?
![image](https://user-images.githubusercontent.com/65740342/116940603-6b60a880-ac2b-11eb-9997-16cde5316117.png)

**Comment by Aedif** [comment]
Hello,

A search field has been added to the 'Art Select' screen. Should be present in release 1.4.1.
