### ISSUE TITLE
Randomizer not appearing to work?

### ISSUE THREAD

**Issue by Orionox** [Aedif/TokenVariants#40]
When I copy-paste a token it's not randomizing the image of the token? I have the copy-paste option selected in the settings, not sure what else I may need.

**Comment by Aedif** [comment]
Hello,

Just to be sure it's setup as so?:

![image](https://user-images.githubusercontent.com/7693704/151557032-70627b54-f660-4350-9212-9f1e0db298f6.png)

You haven't selected to disable it for any reason? (PCs, NPCs, Linked Actor Data, etc.)

Another thing to check would be whether a search performed using the name of the token returns any results to begin with.

![image](https://user-images.githubusercontent.com/7693704/151557374-f2d88ce1-c3f7-45e6-b814-a2bc8b49a9a1.png)

![image](https://user-images.githubusercontent.com/7693704/151557418-63be589f-7658-4794-9380-b1e1afcd0fdf.png)

The randomizer chooses from the images it can find using the tokens name (keywords, and shared images as well if selected) so if it didn't find any it would not assign a random image.
