### ISSUE TITLE
Link Token and Portaits with Randomizer

### ISSUE THREAD

**Issue by JamzTheMan** [Aedif/TokenVariants#41]
Is it possible to also randomize the portrait image when token image is randomized but kept in sync?

E.g. I have in my search paths 12 token/portrait images named like, "Ogre 11.webp" -> "Ogre 11 [Portait].webp"

So if it picks the random token and they is a matching portait, pick that as well? (Assuming I have told TVA what naming pattern portrait images are)

**Comment by Aedif** [comment]
Been doing development on the module again so revisited your suggestion.

This should now be possible via enabling a new randomizer setting introduced in release [1.27.1](https://github.com/Aedif/TokenVariants/releases/tag/1.27.1): **Sync Portrait and Token based on image name similarity**
