### ISSUE TITLE
Feature: Include token wildcard images in HUD please

### ISSUE THREAD

**Issue by orcnog** [Aedif/TokenVariants#42]
Really great module!  I'm loving it, and using it in place of Token HUD Wildcard.  It's streamlined my token image assignments in-game immensely already.

But one feature that Token HUD Wildcard offered, which I feel is missing from TokenVariants, is it included token wildcard images as selectable HUD image options.  I have many many tokens already organized to leverage the token wildcard feature... even though, in some cases, the file names don't exactly work for TokenVariant's search function, and they therefore are not found.

I think it'd be simple to add support for this.  If an image is identified as a potential wildcard image by FVTT, I think it should be automatically included in your search results set.

Example:
![image](https://user-images.githubusercontent.com/70491549/152065566-4de4a43e-96d1-41e8-ba56-40a115a7b8fb.png)

**Comment by Aedif** [comment]
New setting added in release **1.24.0** under 'Token HUD Settings': **Include wildcard images**

Give it a go and feel free to comment here again if you find any issues.

**Comment by orcnog** [comment]
Beautiful.  Thank for the very quick turnaround. Now this module completely replaces Token HUD Wildcard for me!
