### ISSUE TITLE
[Bug] Disable Automatic Pop-ups for On Token Copy+Paste does not work

### ISSUE THREAD

**Issue by Ghostdesu** [Aedif/TokenVariants#43]
**Environment**
FoundryVTT 9.249
pf2e 3.3.1.10273
Token Variant Art 1.24.0

**Describe the issue**
Automatic Pop ups remain enabled on copy paste even with the setting on.

**To Reproduce**
1. Set up Token Variant Art folders.
2. Toggle On Token Copy+Paste on in Disable Automatic Pop ups window.
3. Copy a token.
4. Observe a pop up.

**Expected behavior**
Token selection should not pop up following copy paste if the setting excluding it is enabled.

**Comment by Aedif** [comment]
This was a v9 specific bug. Should now be fixed as of release **1.24.1**

https://github.com/Aedif/TokenVariants/releases/tag/1.24.1
