### ISSUE TITLE
Posture- and condition based variant images

### ISSUE THREAD

**Issue by mikehenry-io** [Aedif/TokenVariants#44]
Thank you for implementing more dynamic token images for Foundry VTT! I have been missing this in Foundry VTT.

I use primarily top-down tokens during encounters in my games, in particular for NPC's. What I would like is to be able to connect the token's image to its current posture or condition. 

For example: a token can be standing, crouched or prone and depending on that posture, the module would set the token's image automatically. Other variants could include standing with a drawn weapon, or aiming with that weapon while standing, crouched or prone. Also, incapacitated characters can have their own image(s) for that condition. Naturally, these images need be defined for an actor or token in advance and connected to the posture or condition the image is valid for.

A different VTT that I have used, was set up with this behavior and this made the GMs life easier, increased the immersive effect, and also giving a clear visual cue to what was going on during an encounter.

**Comment by Aedif** [comment]
Hello,

In version **[1.25.1](https://github.com/Aedif/TokenVariants/releases/tag/1.25.1)** I added the ability to map images to 'Toggle Visibility State, 'Toggle Combat State' and all Status Effects, which depending on the game system you use and any custom affects you might have added yourself might include some or all of the postures you've mentioned.

I'd encourage to give it a go and see if that covers your usecase well enough.

![status_config](https://user-images.githubusercontent.com/7693704/155744276-fb0b2702-5a23-49b7-aa32-9ddcbdb877bb.gif)

**Comment by mikehenry-io** [comment]
This is amazing work! Exactly what I needed. Can't believe I missed your update in Feb.
How do I set the prototype token so that all tokens for a particular actor gets the image states?

**Comment by Aedif** [comment]
The image mappings get attached to the actor, so simply '**Shift+Left-click**' the Status Effect in the Token HUD, assign the image, and the actor associated to that token will now have the mapping. 🙂

**Comment by mikehenry-io** [comment]
That's perfect! I also like ability to set a priority on a state/image and have the highest priority state's image be displayed.
