### ISSUE TITLE
A way to turn off caching

### ISSUE THREAD

**Issue by Bryn1701** [Aedif/TokenVariants#47]
Love your module! But I was curious if there Is there a way to turn off the caching message on start up? It's a bit spammy, specially when testing things and refreshing often. Especially for my players.

![Token Variant Art Caching spam](https://user-images.githubusercontent.com/64208580/157543361-820a115d-6c12-41ef-a0c7-96cc3fa797d5.jpg)

**Comment by Aedif** [comment]
Glad you're enjoying the module. 

I added a setting to turn this off in the latest release:

https://github.com/Aedif/TokenVariants/releases/tag/1.28.1

**Comment by Bryn1701** [comment]
Woo hoo! thank you so very much!
