### ISSUE TITLE
[Incompatibility] Token Mold

### ISSUE THREAD

**Issue by Orionox** [Aedif/TokenVariants#49]
When using the module token mold, randomization of token art breaks unless the option for set token creature sized and scaled to map scale is ticked.

**Comment by Aedif** [comment]
Am unable to reproduce this. Seems to work fine with the option ticked and unticked:


https://user-images.githubusercontent.com/7693704/159262901-3f9bdbd6-3a1c-4643-9ff1-de9e7228cf48.mp4

**Comment by Orionox** [comment]
When I get home ill post the error I'm getting when I do it. Sorry for not posting it in the original message.

**Comment by Orionox** [comment]
https://youtu.be/BNxV8RnO4Hk
the video I took was too big

**Comment by Orionox** [comment]
![Capture](https://user-images.githubusercontent.com/20059838/160040710-a3c89e9b-394f-4fe4-88f0-465cb5470064.PNG)
i do get this error when the option is ticked

**Comment by Aedif** [comment]
I'm unable to view the video as it has been set to private.

**Comment by Orionox** [comment]
Should work now

**Comment by Aedif** [comment]
Unable to reproduce the issue. If the problem persists feel fre to re-open and provide more information.
