### ISSUE TITLE
Work with SWADE

### ISSUE THREAD

**Issue by JaySK015** [Aedif/TokenVariants#5]
Is there a way to get this module to work with the game system swade?

**Comment by Aedif** [comment]
Hi,

I removed the system limitation. It was simply there because I only tested on dnd5e system, but the module should be agnostic to any one of them.

Update to release 1.4.2

**Comment by JaySK015** [comment]
Your module works perfectly with SWADE.  No issues at all.  TokenVariants
is great, thank you for the work!

Jason
