### ISSUE TITLE
Token doesn't update when display separate pop-ups is unchecked.

### ISSUE THREAD

**Issue by friction1** [Aedif/TokenVariants#50]
When this box is unchecked, now only the actor updates and not the tokens for the actor. 
https://user-images.githubusercontent.com/11384891/159172505-95d0eb58-0901-4f8a-b00d-496f3985e833.mov

**Comment by Aedif** [comment]
This should be fixed in Release [1.28.2](https://github.com/Aedif/TokenVariants/releases/tag/1.28.2)
