### ISSUE TITLE
[bug] Multi-word actors can't find token

### ISSUE THREAD

**Issue by txm3278** [Aedif/TokenVariants#53]
Token Images not being found for actors with multi word names (ex. Riding Horse with the png titled "Riding Horse.png"). Search by Keyword is enabled

**Comment by Aedif** [comment]
Hello,

It appears to be working fine for me with the Keyword search enabled. 

![image](https://user-images.githubusercontent.com/7693704/162592943-babdb9bc-dcbe-4658-840a-7c44cdfb90c8.png)
![image](https://user-images.githubusercontent.com/7693704/162592950-3ab0527a-2e4f-4794-b9ce-6fdce2e579cf.png)
![image](https://user-images.githubusercontent.com/7693704/162592964-55905c85-6a95-4b40-a366-3d608669fff2.png)

I did find an issues related to the '**Match name to folder**' setting however which I will fix. (full name Riding Horse is not being matched, keyword search finds it though)

Regarding your issue... are you using any filters which might be filtering this art out? If you search just 'Riding' or 'Horse' is the art still not found?

**Comment by txm3278** [comment]
I have 'Match name to folder' enabled although the 'Riding Horse' I'm looking for is not a folder. Searching 'Riding' or 'Horse' correctly finds the art

**Comment by Aedif** [comment]
This should be fixed in release [1.28.3](https://github.com/Aedif/TokenVariants/releases/tag/1.28.3), try updating and see if it's resolved.
