### ISSUE TITLE
Issue with Randomizer

### ISSUE THREAD

**Issue by skellitor301** [Aedif/TokenVariants#54]
Hello, from what I understand the randomizer allows for the token to randomly pick one of the cached images that matches the token's name upon creation/copy+paste correct? If so then I'm having trouble getting that to work, it keeps pulling the same image that I first selected when the actor is made and put in the compendium. I've tried pulling from both and I get the same result, and I've tinkered with the randomizer settings but to no avail. I've tried reading the instructions on the addon page but it doesn't help with this issue. Is there something wrongly set in my settings or could it be something else?

attached are settings I've tried and neither seem to want to work:
![firefox_vuMYgvmFky](https://user-images.githubusercontent.com/3630718/162581977-0099f55c-186d-4c71-8709-6e6f6dfb192f.png)
![firefox_DQBZaxvI0L](https://user-images.githubusercontent.com/3630718/162581979-3707fe40-9655-4959-a36e-00fad6c6f50a.png)

**Comment by Aedif** [comment]
A quick sanity check: as per your settings Randomizer is disabled for NPC actors. So just to make sure your issue is that randomizer is not being applied for PCs and vehicles? Or were you performing tests and expecting randomization to be done on NPCs?

**Comment by skellitor301** [comment]
My goal was to only apply it to npc's since my players don't have multiple versions and I don't use vehicles yet. Also the option is checked for NPC actors right?

**Comment by skellitor301** [comment]
Oh wait I see what you mean, I did not see the "Disabled for" part, my brain read "Enabled for"

Let me test that real quick.

**Comment by skellitor301** [comment]
Yes, that was it. Sorry about that, like I said I confused reading disable with enable for some reason.

**Comment by Aedif** [comment]
No problem. I asked because the wording of these settings can be confusing. Glad you got it working in the end 👍
