### ISSUE TITLE
Status Effect will not change token picture on linked tokens

### ISSUE THREAD

**Issue by RavenknightDM** [Aedif/TokenVariants#55]
Hiya, first a big great thank you for this marvelous mod.
Now I have problems with linked tokens and settings regarding status effects. Having a image for stunned, defeated etc. works great for mooks but not for player characters and other linked creatures. Is there a setting I can have missed? (Wouldn't be the first time.)
Forgot to add: The combat images work just fine. Its only the status effects that I can't get to work.

**Comment by Aedif** [comment]
Glad you're enojying the module 🙂 

The issue with the linked tokens should be fixed in release [1.29.2](https://github.com/Aedif/TokenVariants/releases/tag/1.29.2)
