### ISSUE TITLE
[Request] - disable art selection for non-GMs

### ISSUE THREAD

**Issue by dmrickey** [Aedif/TokenVariants#56]
As the GM, I still like to select token alternates when dropping a token on the scene (or quickly closing it). I don't my players to have that option, so it would be nice if there was an option for that.

**Comment by Aedif** [comment]
I assume your players have '**Configure Token Settings**' and '**Use File Browser**' permissions?

In general module allows for unrestricted Token HUD button, Art Select pop-up, Actor sheet portrait right-click, and Token Configuration's new image button access if those permissions are enabled.

Is it just the pop-up that you'd want disabled or all of the above?

**Comment by dmrickey** [comment]
I don't really care what modifications my players make so I have it pretty open as far as things they own. But I also don't want (nor do they) additional pop ups in the middle of them dragging a token in. So specifically the only thing I'm asking is for a way to make it so that, when a token is dragged onto a scene, a GM can still get the popup for choosing other art while a player doesn't.

Right now I've just got the option disabled for disabling the popup when spawning tokens as I (as the GM) don't often change the art for created tokens, but it would be nice to keep that option for me while disabling it for my players.

**Comment by Aedif** [comment]
New setting added under '**Pop-up Settings**': **'GM Only'**. 

Available in release [1.31.1](https://github.com/Aedif/TokenVariants/releases/tag/1.31.1)
