### ISSUE TITLE
Players get "Lacks Permission to Update" Error for Status Images

### ISSUE THREAD

**Issue by megahead11** [Aedif/TokenVariants#57]
![img](https://cdn.discordapp.com/attachments/722566083499786352/969812624776773642/unknown.png)

This will pop up for players whenever a token gains an effect that would change the token. While it still runs the change, the error pops up for all players, but not the GM.

**Comment by Aedif** [comment]
Resolved as of release [1.32.3](https://github.com/Aedif/TokenVariants/releases/tag/1.32.3)
