### ISSUE TITLE
suggestion: export settings file. 

### ISSUE THREAD

**Issue by jacksands** [Aedif/TokenVariants#58]
this is an amazing module with a lot of options and settings, can you create the possibility to export the module settings so it would be easier to implement it in new worlds?

anyway thanks for all your work!!!

**Comment by Aedif** [comment]
New setting added in release [1.33.1](https://github.com/Aedif/TokenVariants/releases/tag/1.33.1): **Import/Export**

**Comment by jacksands** [comment]
Tks!
