### ISSUE TITLE
[Bug?] Switching to Battle and Normal token states ignores priority

### ISSUE THREAD

**Issue by megahead11** [Aedif/TokenVariants#59]
I noticed that regardless of how low you set the priority of the battle state, the image will always change to and from the normal token and battle state regardless of any status images set. 
For example, if you have an image set to "bloodied", and then toggle combat on, it will ignore it even if the priority of the "bloodied" image is higher. Likewise, if you're in battle, and the token becomes bloodied, the image will change. But if you exit combat, it will lose the image of "bloodied" for the normal image.

**Comment by Aedif** [comment]
Should be fixed in release [1.32.4](https://github.com/Aedif/TokenVariants/releases/tag/1.32.4)
