### ISSUE TITLE
Select Variant popup appears many times.

### ISSUE THREAD

**Issue by kainan613** [Aedif/TokenVariants#6]
Whenever I put in a new actor and the select variant window pops up, it spawns 3, or 6, or 12 windows. I don't know why it's different every time, but that's how it is. The Windows are all on top of each other so I basically have to press the close button 3, or 6, or 12 times.
 
If I go to a tokens settings, the Select Variant button under "Image" appears as many times as the windows (3 and up, until about 6 when it can't display any more.

Other than that love the module, thank you for your work and your time!

**Comment by Aedif** [comment]
Hello,

This should be fixed in release 1.4.3.

The problem arises when switching between scenes. Switching between scenes 5 times would result in 6 windows being displayed, switching 6 times would display 7, etc.

The bug was introduced in release 1.3.2.
