### ISSUE TITLE
Latest Update Broke

### ISSUE THREAD

**Issue by friction1** [Aedif/TokenVariants#60]
The module no longer seems to do anything in my Foundry. I can turn it on and change the settings but it isn't saying that it's loaded the art when I first start my world and none of the module's functionality works. I have tried turning off all other modules and the problem persists. Running the latest foundry and d&d5e.

**Comment by Aedif** [comment]
Do the Token Variant Art setting appears under Module Settings?

If not could you also press F12 and check if at the top of the console you can see any errors?

**Comment by Aedif** [comment]
If you press F12 can you see any errors showing up when you attempt to do anything related to the module?

**Comment by friction1** [comment]
Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: token-variants]
    at ClientSettings.get (foundry.js:2150:42)
    at fetchAllSettings (settings.js:381:48)
    at registerSettings (settings.js:369:9)
    at initialize (token-variants.mjs:54:9)
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5567:11)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)

**Comment by friction1** [comment]
I'm running Version 9 - Build 269

**Comment by Aedif** [comment]
I was able to reproduce this, seems to be 9.x specific, which is odd since the changes I made should have been version agnostic.

**Comment by Aedif** [comment]
Alright I got a fix for the problem, will push out a new version in a few minutes.

**Comment by Aedif** [comment]
The update is out [1.33.2](https://github.com/Aedif/TokenVariants/releases/tag/1.33.2)

Sorry about this. I usually test bigger updates on both v8 and v9, but I didn't expect this one to behave differently on either version.

**Comment by friction1** [comment]
No problem at all. I am extremely grateful for this module. Glad I could help.
