### ISSUE TITLE
[conflict] Token Magic FX

### ISSUE THREAD

**Issue by RavenknightDM** [Aedif/TokenVariants#62]
Hiya, as always, a great big thanks for this wonderful mod.

This isn't so much a bug as a mod-conflict so I'm not sure if you're interested or not but here goes.

Now, I've noticed that since the last update any tokens with active Token Magic FX effects on them will have the effect turned off every time I load scene. The effect can be re-applied without error and if I use Variant Token Art to change the look of the token the effect will reappear. It's a bit of a mess to mess with all the tokens on a scene though since I tend to use a lot of shadows. :)

Thanks
/Ravenknight

When loading the  scene. Albert has no shadow.
![Albert 1](https://user-images.githubusercontent.com/53635985/169982463-b997368c-0351-4fa0-b54c-598bb9f0da0b.png)

Upon switching token art. Albert's shadow reappears.
![Albert 2](https://user-images.githubusercontent.com/53635985/169982551-3faabc72-5946-42d8-b8d3-9bd4007014c2.png)

When returning to the original token art. The shadow remains.
![Albert 3](https://user-images.githubusercontent.com/53635985/169982624-d7c8308c-fdc9-4484-821d-baf0cf1865da.png)

**Comment by Aedif** [comment]
This actually helped me identify a bigger issue with the new functionality that I recently added. I got a fix for this which I'll include in the next update.
