### ISSUE TITLE
Can you make it for Tiles?!!

### ISSUE THREAD

**Issue by jacksands** [Aedif/TokenVariants#63]
Your module is amazing! lots of options! very powerful!
can you take in consideration make the same for tiles? maybe even on the same module? 
that would be terrific!

tks anyway for your amazing work!
Erich

**Comment by Aedif** [comment]
Hi, the concepts of "**token**" and "**portrait**" are are hardcoded into almost every aspect of this module, generalising or attaching on tiles to that would be rather difficult... and anyway this would be going beyond the scope of what this module is trying to achieve (It's called >**Token**< Variant Art after all 😄). 

I already had concerns from some people considering installing the module about it being too "heavy/complex", the amount of additional settings I'd need to add to control for tiles would be exacerbating the issue.

If I do work on this, it would probably manifest as a separate module. I'll consider it, but will not be making any promises 🙂

**Comment by Aedif** [comment]
Yes, I'll work on it a bit more later. This is the first attempt at integrating tiles into the module. It was easier than I thought it would be. The feature set is not as complete as with the tokens, but it's something for now.

**Comment by Aedif** [comment]
Made a few more additions to Tiles in release [2.8.0](https://github.com/Aedif/TokenVariants/releases/edit/2.8.0)

This will be all the changes I will make regarding tile support for now so I'll be closing the issue.

**Comment by jacksands** [comment]
Tks!
You are on fire on this module!
it is amazing!
