### ISSUE TITLE
Save individual token config lines within a tab

### ISSUE THREAD

**Issue by Nargath** [Aedif/TokenVariants#65]
Is there a way to see some parts of a tokens config with an image?

I've got two states of tokens, a ringed portrait, and a topdown token. First one is used out of combat, the second is for in combat.
I've got the auto-switching set up to go back and forth between the two tokens when combat is toggled on or off.

I also use Auto-Rotate to allow the combat token to rotate dynamically with its movement.
So on the combat token, I have saved the Appearance tab config, and forced the Autorotate option to On, and on the portrait token, I've set it to Off.
Which works, they stop rotating out of combat.

The problem is, is that the orientation of the token then copies from one token to the other.
So if my combat token walks north, then they drop out of combat, when it switches back to the portrait token, the image is upside down, cos the rotation has changed.

But if I save the Character tab config, so I can set the rotation to 0 degrees, it also saves all the other options on that tab, including the  coordinates.
So when I come out of combat, my token is orientated the right way, but its moved to a default set of coordinates across the map.
And when I drag the token onto a new map, the token automatically goes to those locked coordinates as well.

Is there a way of saving some options within a tab?

**Comment by Aedif** [comment]
Hi,

There is no way to do this at the moment. To be honest I thought no one besides me was even using this particular module feature 😄 . Saving the entire tab was working for me so I didn't bother touching it again.

I'll see how difficult it is to implement and might include some means of providing finer control over which particular fields get saved in the next module update.

**Comment by Nargath** [comment]
Not a drama, it’s not a huge thing of it proves WAY more difficult than it’s worth.

just means that when I turn off combat, I’ll need to highlight the pc’s tokens and use keyboard commands to reorientate them

**Comment by Aedif** [comment]
It's not that bad. Was able to produce something that seems to work:

https://user-images.githubusercontent.com/7693704/172164176-60fbd26c-5b97-4ede-b22f-bdc595c857af.mp4

Will need to wait a bit for the update though. I've made quite a few changes to how settings are saved in the module and I need to test everything out before I push a new release out.

**Comment by Nargath** [comment]
Amazing! Thanks so much!
If it all works out, more than happy to wait for a release :)

**Comment by Aedif** [comment]
The new way to assign configs to images is now present in release 2.0.0
https://github.com/Aedif/TokenVariants/releases/tag/2.0.0

All your previous configs should continue to work.
