### ISSUE TITLE
Sound bug when video shows on hud

### ISSUE THREAD

**Issue by jacksands** [Aedif/TokenVariants#66]
Hi again! first tks for the amazing module!

I have come across a strange "bug".. if a video with sound shows on the token hud and you open the selection hud, it will immediately plays the sound at maximum volume, ignoring any volume setting on foundry, and stay playing in loop, even if you close the hud, unless another token is selected, selecting the first token make it play again!

last nigth I was playing when a token has the same name as a video, "shooter", all the sudden an insanely loud shooting started..kkk at least is just for me, I think it only affects the person selecting the token.

the only way to make it stops was to remove the video from the folder and CTRL+F5 to reset the cached images.

It's actually amazing that the module cam find videos, like mp4 or webm, but can you take a look about the sound? nade it mute or something? 

to test just use an webm or mp4 video with sound and use it in a way that the hud can find, like same name or folder... just make sure to adjust the volume before, specially with headphones...kkkk

once again thks!

Erich

**Comment by Aedif** [comment]
Ah, that is a bit of a problem 😄 , easy to fix. I never realised the module did that. 

Should be fixed in release [2.1.1](https://github.com/Aedif/TokenVariants/releases/tag/2.1.1)

**Comment by jacksands** [comment]
TKS man! really appreciate!
