### ISSUE TITLE
Feature Request: Portrait Support

### ISSUE THREAD

**Issue by JamzTheMan** [Aedif/TokenVariants#7]
Loving what I'm seeing so far! I'm looking to replace compendium mapper (mostly because it needs to be ran after every system update).

Would it be possible for your module to also support setting the Portrait as well as Token art? Ideally there would be configuration for if an image name ends in xyz.extenstion (or blank) it would use those images.

e.g. I have all my "portrait" images saved as "Some Creature [Portrait].webp". I imagine others may have .token.webp and .avatar.webp, etc.

**Comment by Aedif** [comment]
If you've wished for automatic assignment of portrait art that's not really in the spirit of this module.

However as of release 1.5.1 I added a couple of settings to the module that might **mostly** accomplish what you want.

Portrait and token art can now be set separately upon actor/token creation, and right-clicking on the portrait in the Actor Sheet will bring the popup as well.

Additionally **Portrait art filter** and **Token art filter** module settings can be used to filter portrait and token art from the popups. 

For your example you'd set **Portrait art filter** to "[Portrait]", which would cause popups opened for the portrait art selection to only include files containing that text in their names.

**Comment by Aedif** [comment]
Closing for now. Feel free to comment under this issue again if you think this could have been implemented better.
