### ISSUE TITLE
[Suggestion] Add option to show full path on token HUD mouse hover 

### ISSUE THREAD

**Issue by dirusulixes** [Aedif/TokenVariants#70]
Just a qol suggestion as per title. I have ~~too~~ many tokens and the full path would sometimes help me understand which ones I'm looking at 
![image](https://user-images.githubusercontent.com/5693623/174445437-1c4203c3-7621-48b9-afa8-f5c38c3b9dc7.png)

**Comment by Aedif** [comment]
Cought me at a good time. I was just about to push out a new release and this was pretty easy to add. 

Checkout release [2.10.0](https://github.com/Aedif/TokenVariants/releases/tag/2.10.0) at your convenience 🙂
