### ISSUE TITLE
Issue to Configure Settings

### ISSUE THREAD

**Issue by Flylicorne** [Aedif/TokenVariants#71]
Using the module v2.10.1 on Foundry VTT with all others module deactivated.
I tried to uninstall/reinstall it as well and same error appears.
When i try to configure settings and click on Settings, nothing Happen.

foundry.js:319 TypeError: Cannot read properties of undefined (reading 'startsWith')
[Detected 3 packages: token-variants, colorsettings, lib-wrapper]
    at ConfigureSettings._pathIcon (configureSettings.js:465)
    at configureSettings.js:61
    at Array.map (<anonymous>)
    at ConfigureSettings.getData (configureSettings.js:58)
    at ConfigureSettings._render (foundry.js:3062)
    at ConfigureSettings._render (foundry.js:3764)
    at ConfigureSettings.render (foundry.js:3021)
    at ExtendedSettingsConfig.onClickSubmenuWrapper (colorSetting.js:20)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:595)
    at ExtendedSettingsConfig.🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:189)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
    
    + Before the update, when a token was send to the board, a popup appears to select another token image. Since, the update, nothing appear anymore.

**Comment by Aedif** [comment]
Hi,

I think your search paths got corrupted somehow. 

Mind running the following in console?:

```game.modules.get("token-variants").api.TVA_CONFIG.searchPaths```

![image](https://user-images.githubusercontent.com/7693704/175427403-13c5129f-aa2e-43fa-af13-24d33d3cd44d.png)

You should see something similar to the example above ^

Do you notice any ``source:`` missing or being equal to NULL or 'undefined'?

**Comment by SR5060** [comment]
This happened to me as well. I was able to use your code to clear and remap and that fixed it, but wanted to flag in case there was something funky causing the corruption.

**Comment by Aedif** [comment]
If you saw it do you perhaps remember if any of your paths were missing "source"? If you do what type of path was it (data/s3/rolltable etc)

**Comment by SR5060** [comment]
Sorry, I didn't bother checking since I was confident your fix would work. But I only had "data" directories listed previously

**Comment by Flylicorne** [comment]
> game.modules.get("token-variants").api.TVA_CONFIG.searchPaths = []

Hi,

Thank you, i am able to open the settings now. 
Huge thanks for your assistance on it.

**Comment by Flylicorne** [comment]
Is there a reason i dont see the Variant pop up when i move a Token on my board game.
In the past version, when i move a token to the game board, a pop up appear to change the token image. It doesn't appear anymore now.
Is that expected behavior ?

**Comment by Aedif** [comment]
Pop-ups can be enabled/disabled through various means.

If you want the pop-ups to appear first make sure that they're not disabled for the actor type you're dragging onto the board and that `On Token Create` is unchecked here:

![image](https://user-images.githubusercontent.com/7693704/175766000-2d91c2b1-3f65-45c1-8369-543760abf25c.png)

Also make sure that you have the permissions enabled:

![image](https://user-images.githubusercontent.com/7693704/175766030-e6b21f65-8725-4590-8abb-95fa3e8155b3.png)

If you're using the randomizer then that will be prioritized over opening the pop-up. For example if randomizer is set to randomize the token image on `Token Create` then the pop-up will not be displayed:

![image](https://user-images.githubusercontent.com/7693704/175766135-051bfcaa-39af-4f42-ac70-549e38418439.png)

If you want randomization but would also like the pop-up displayed for tokens that are not being randomized then enabled `Show Art Select pop-up if randomization is disabled`

And lastly you can override some of the pop-up settings for a particular token/actor via Shift+Left-Clicking the 'Token HUD button':

![image](https://user-images.githubusercontent.com/7693704/175766239-84bfffbf-af17-4d13-a063-cb0dec4d1893.png)


I realise it's a lot, however it's to allow users to really fine tune the behaviour of the module 😅

**Comment by Flylicorne** [comment]
Here my settings and still no pop up :

![image](https://user-images.githubusercontent.com/108094453/175774897-02294858-e437-419d-838b-f1e9987d96f6.png)

![image](https://user-images.githubusercontent.com/108094453/175774913-7a08e5d8-28e3-4cb6-8155-887218dc6dbe.png)

![image](https://user-images.githubusercontent.com/108094453/175774931-b5559ef0-06db-4d7e-83d5-ec39f19a32e0.png)

![image](https://user-images.githubusercontent.com/108094453/175774949-dc3f818d-4ac9-4044-98b6-8715fd5f7f54.png)

![image](https://user-images.githubusercontent.com/108094453/175774968-9329acb4-f802-4ef6-a13d-8c1a932512d4.png)

![image](https://user-images.githubusercontent.com/108094453/175774986-dd3504b9-a207-43fd-bb11-5ab63f5ac07b.png)

![image](https://user-images.githubusercontent.com/108094453/175775007-3ca76959-bc94-4d3f-9c46-0f66be31fca1.png)

![image](https://user-images.githubusercontent.com/108094453/175775028-f6580eec-0e72-43a5-b929-9412d158d6ce.png)

Token HUD client settings :

![image](https://user-images.githubusercontent.com/108094453/175775054-886c6b0d-5702-420f-abea-4f3b67446f90.png)

Compendium Mapper

![image](https://user-images.githubusercontent.com/108094453/175775075-a10abf61-80a8-464f-8d50-d470c5a66604.png)

**Comment by Flylicorne** [comment]
I just update to the last version 2.11 and Pop Up appears now with the same settings.

**Comment by Aedif** [comment]
Hmm flad to know it's working for you. I didn't actually find the source of the problem but I made the module tolerate the missing **source** a bit more.

According to your settings the pop-ups should have been appearing in the older versions too.

If it wouldn't bother you too much, would you mind exporting the settings and posting the file here? If you rename the file to **token-variants-settings.txt** you should be able to just drop it in the text box.

![image](https://user-images.githubusercontent.com/7693704/175776311-36974026-cfec-466a-82d0-4905fc7d2e50.png)

This would allow me to exactly replicate the settings that you have and actually fix the source of the problem.

**Comment by Flylicorne** [comment]
Here the file 

[token-variants-settings.txt](https://github.com/Aedif/TokenVariants/files/8984876/token-variants-settings.txt)

**Comment by asdexter** [comment]
Hello, I'm having the same issue as OP, but when I used the console command you provided

game.modules.get("token-variants").api.TVA_CONFIG.searchPaths = []

, a second error pops up when I try to access the module settings

TypeError: Cannot create property 'label' on string ''
[Detected 1 package: token-variants]
    at ConfigureSettings.getData (modules/token-variants/applications/configureSettings.js:75)
    at ConfigureSettings._render (foundry.js:3062)
    at ConfigureSettings._render (foundry.js:3764)
    at ConfigureSettings.render (foundry.js:3021)
    at SettingsConfig._onClickSubmenu (foundry.js:55705)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

I wonder if the easiest fix for this is to post an exported default settings txt file so that I can import and reset the settings, since for whatever reason the migration between versions seems to have failed (just guessing). Thanks!

**Comment by Aedif** [comment]
Along with that command could you also run:

``game.modules.get("token-variants").api.TVA_CONFIG.searchFilters = { "Portrait": { "include": "", "exclude": "", "regex": "", "label": "Portrait" }, "Token": { "include": "", "exclude": "", "regex": "", "label": "Token" }, "PortraitAndToken": { "include": "", "exclude": "", "regex": "", "label": "PortraitAndToken" }, "Tile": { "include": "", "exclude": "", "regex": "", "label": "Tile" }, "Item": { "include": "", "exclude": "", "regex": "", "label": "Item" }, "JournalEntry": { "include": "", "exclude": "", "regex": "", "label": "JournalEntry" }, "Macro": { "include": "", "exclude": "", "regex": "", "label": "Macro" }, "RollTable": { "include": "", "exclude": "", "regex": "", "label": "RollTable" } }``

Then open the 'Configure Settings' window and make sure you press 'Save Changes'.

I'll look into adding a fix for this in the next module release that will not require execution of such commands.

**Comment by Aedif** [comment]
If you are yet to try out the fix I recommended above I'd recommend updating to [3.4.0](https://github.com/Aedif/TokenVariants/releases/tag/3.4.0). I made some fixes that should hopefully resolve this issue.

**Comment by asdexter** [comment]
Hey thanks for the update, this resolved the issue!

**Comment by Aedif** [comment]
All brought up issues should be resolved now. Feel free to comment or re-open the issue if any related problems pop-up again.
