### ISSUE TITLE
[enhancement] static cache wipes on update

### ISSUE THREAD

**Issue by SR5060** [Aedif/TokenVariants#72]
the static cache is removed when the module is updated, as it is stored in the module folder, but the system does not automatically refresh the cache, requiring a manual refresh. Not a huge issue, but would be a nice enhancement to have the system automatically refresh the cache if static cache is set and the module is updated

**Comment by Aedif** [comment]
Hi,

Made some improvements in the latest release [2.13.0](https://github.com/Aedif/TokenVariants/releases/tag/2.13.0).

The module will now re-cache and save a new file automatically, but if you wish you may now specify a location for the cache file that is outside the module folder, circumventing the problem completely.
