### ISSUE TITLE
[Feature Request] Ability to adjust transparency of overlays for conditions. 

### ISSUE THREAD

**Issue by jinkergm** [Aedif/TokenVariants#73]
Not sure if it's possible since it seems the effect is attached to the token, but a way to adjust transparency for just the overlay would be nice.

**Comment by Aedif** [comment]
As of release [3.1.0](https://github.com/Aedif/TokenVariants/releases/tag/3.1.0) you should now be able to adjust overlay opacity as well as a number of other settings.
