### ISSUE TITLE
Reconnecting with GM account reverts token images on canvas to prototype defaults

### ISSUE THREAD

**Issue by dirusulixes** [Aedif/TokenVariants#74]
fvtt 9.269
TokenVariants 3.3.2

When players have been changing their tokens images using the HUD and I reconnect with my GM account, all players' tokens on the canvas go back to their prototype token default images. I'm not sure if this is to be expected or a bug.

**Comment by Aedif** [comment]
Are you using ATL by any chance? It is a known issue that ATL reverts tokens back to their prototype settings: 
https://github.com/kandashi/Active-Token-Lighting/issues/100
https://github.com/kandashi/Active-Token-Lighting/issues/107

If so one way to get around this would be to enable the following setting in TVA:

![image](https://user-images.githubusercontent.com/7693704/180337457-63de1755-98a1-488d-bda5-4e733bdda1d0.png)

This will transfer any updates your players make using TVA to the prototype as well

**Comment by dirusulixes** [comment]
thanks, that was indeed what was happening. I had completely missed ATL's behaviour. 
Actually the update prototype settings works perfectly for me. I cannot think of any downside to enabling it.
