### ISSUE TITLE
Searching doesn't work on folders that aren't cached

### ISSUE THREAD

**Issue by karpana** [Aedif/TokenVariants#79]
This used to work, and broke somewhere along the way...

I have a large library of images that I have (from the Paizo PDF token kits) that are cached, and a smaller library of "one-offs" I used for my campaigns where I add specific imagery for unique creatures and NPCS.

my configruation of search paths looks like this
![image](https://user-images.githubusercontent.com/15716173/188287115-db27ae8d-7333-44ed-9afc-17078e588d8e.png)

The problem is that those 3 'not cached' folders no longer get searched when I'm creating an actor.
if I simply fill the checkbox in, it works fine, but then new additions to the folder don't show up unless I force a rebuild of the image cache.

Please fix this so that "uncached" folders are properly searched.

**Comment by Aedif** [comment]
Hi, This should now be fixed in release [3.6.1](https://github.com/Aedif/TokenVariants/releases/tag/3.6.1)

**Comment by karpana** [comment]
Wow @Aedif That was an unexpectedly quick turnaround.  

I've confirmed that it's working as it should!
(and this issue can now be closed)

Thank you!!!
