### ISSUE TITLE
Feature Request: Support selection popup from Actor menu

### ISSUE THREAD

**Issue by JamzTheMan** [Aedif/TokenVariants#8]
Would be awesome if you also got a "popup" when dragging from the Actor menu. It seems to only pop if you drag from a compendium?

FWIW I'm using PF2E system which uses different default images (vs mystery man) based on race IIRC so not sure if that makes it harder to detect if it has a base image or not?

Alt solution, dragging from Actor menu while holding ctrl or shift or alt or something configurable would pop up the selection screen? (So you may have a default "Ogre" but each drag could also drop a random Ogre token/portrait?)

**Comment by Aedif** [comment]
As of release 1.5.1 the popup will now also be shown when dragging in an actor from the Actor Directory if the appropriate key is held.

The key used to trigger the popup is set using the new **Art Directory Popup key** config.
