### ISSUE TITLE
Error= Can't wrap 'Token.prototype._refreshIcon', target does not exist or could not be found.

### ISSUE THREAD

**Issue by Ringelrun** [Aedif/TokenVariants#81]
This error happens on my local install of version 9, but not on my server hosted version 10.

Here is full error from Console:

![image](https://user-images.githubusercontent.com/112992020/188762051-77cee412-229e-47b1-9d91-dd68a46f8ee2.png)

**Comment by Aedif** [comment]
What game system are you running the module in?

also if you select a token and run the following in the console, what sort of output do you get?:
``_token._refreshIcon``
``_token.refresh``

This is what I'd expect to see:
![image](https://user-images.githubusercontent.com/7693704/188763993-b9217fb8-ccda-4ad5-8a9d-96ce248b4570.png)

**Comment by Ringelrun** [comment]
Thanks for getting back with me so quickly!

I'm running Windows 10

[image: image.png]

When I run the lines in console, this is what I get:

[image: image.png]

**Comment by Aedif** [comment]
I can't see the images you tried to link to me. They appear as ``[image: image.png]``

If you could could type out or otherwise provide the Foundry version you're using and the game system you're running that would be really helpful.

I've tested the module on DnD5e on both v9 and v10 and they both appear to work.

**Comment by Ringelrun** [comment]
Sorry, here are the images:

![image](https://user-images.githubusercontent.com/112992020/188975177-40bdacfc-2240-421b-ab95-1c3c462bbe74.png)

![image](https://user-images.githubusercontent.com/112992020/188975252-e02d8767-611a-4b11-ad47-4925e5cb8bd4.png)

**Comment by Aedif** [comment]
Try updating to version 3.6.2 of the TVA module. This should hopefully be fixed.

**Comment by Ringelrun** [comment]
Thanks. When I tried just now by using the update modules screen, it's blocked from updating. The message pop up said it's for version 10, and since I'm still on 9 it's keeping it from taking the update.

![image](https://user-images.githubusercontent.com/112992020/189216635-168ae045-19ea-463f-827e-9c4a8479f159.png)

Is there a specific manifest file/location for the 3.6.2 version?

**Comment by Aedif** [comment]
Oh that's odd, try uninstalling the module. You should be presented with version 3.6.2 when re-installing. All the module settings will be preserved so it should be the same as doing an update.
