### ISSUE TITLE
[Enhancement] Allow picker on right click for Actions

### ISSUE THREAD

**Issue by Truncated** [Aedif/TokenVariants#82]
Right clicking on the Token icon works like a champ
![image](https://user-images.githubusercontent.com/14208325/189724434-9c9117fa-879c-49da-ad63-5c6844573e48.png)
(expected to be blank results for token)

Doing the same for requipment works great
![image](https://user-images.githubusercontent.com/14208325/189724546-b3648130-9b2e-47e3-a60c-ba2018af9acb.png)

Could the same be implemented for Actions?
![image](https://user-images.githubusercontent.com/14208325/189724787-167d367f-ada0-44ee-a775-fdd2aa5c5016.png)

Foundry v9.280
PF1e 0.81.3
Token Variant 3.70

**Comment by Aedif** [comment]
Should now be possible in release [3.7.1](https://github.com/Aedif/TokenVariants/releases/tag/3.7.1)
