### ISSUE TITLE
Token scale not saved in per-variant config

### ISSUE THREAD

**Issue by benbarbour** [Aedif/TokenVariants#83]
I can get the token variant settings to work for the "Tint Color" and "Token Opacity" settings, but not "Scale" or "Dimensions"

**Comment by Aedif** [comment]
I assume you're using Foundry v10? I had a similar issue with another module. Will have a look at this when I get some time.

**Comment by Aedif** [comment]
Should be resolved in release [4.2.1](https://github.com/Aedif/TokenVariants/releases/tag/4.2.1)
