### ISSUE TITLE
Enhancement - Show Description in Compendium Mapper for Items

### ISSUE THREAD

**Issue by Truncated** [Aedif/TokenVariants#84]
The Compendium Mapper is awesome. I didn't realize that you could progress to the next item by selecting in the name field and hitting enter for quite a while instead of clicking "X Close" on the top right; that would be helpful to include in the wiki.

I'm currently mapping graphics to thousands of assets, and I'm finding that the names of things don't always clearly line up to the description of what it should look like. I think Items (and maybe Journal Pages) are primarily the only type that would benefit from showing the item description in the dialog. I've mocked up what this might look like as an example (existing vs. suggested).

This might be optional, defaulted to off for speed, and changable in the module settings with a simple checkbox.

**Existing:**
![image](https://user-images.githubusercontent.com/14208325/194333792-028a4925-573b-4909-896f-8c5622d3945a.png)

**Suggested:**
![image](https://user-images.githubusercontent.com/14208325/194333821-64c5d178-ebb6-4b93-bfdd-35e747b1e9da.png)

**Comment by Truncated** [comment]
Another display method might be to leave the screen layout as-is and provide the description as a tool-tip when you hover on the Current Image at the top.

It would also be helpful if the window that shows was made in two sections, with the line just below the "Clear Queue" button and search term field, so that the results are in a scrollable window area but you always have the description and search text quickly available to compare. Helpful when you're searching through 100 rings to find one that "matches". ;)

**Comment by Aedif** [comment]
Was meaning to do the sticky header a while ago but never came to it. Will include it in the next release. The descriptions should be doable as well.

**Comment by Aedif** [comment]
Description and sticky header should be present in the latest release.
