### ISSUE TITLE
Enhancement - Start and Return cursor location to end of text in search field after image selection in CM

### ISSUE THREAD

**Issue by Truncated** [Aedif/TokenVariants#86]
Finding that hitting Enter if the cusor is in the text field has made the Compendium Mapper MUCH smoother and quicker to use, however it's still tedious to click back and forth for each. item. when you have 3k to go through. :)

Please have the window set the cursor focus to the end of the text in that field for each queue item.
Apologies if I'm off the mark on how you might implement this, but here's what I mean in Javascript: https://stackoverflow.com/questions/511088/use-javascript-to-place-cursor-at-end-of-text-in-text-input-element

and here's where on the screen I mean:
![image](https://user-images.githubusercontent.com/14208325/194379712-ad04fb88-c03f-487d-8af4-0a10bc63a2c1.png)

This allows me to keep the cursor down by where the icons I usually end up choosing are while using Enter to quickly move to the next if I don't have one to choose yet.

**Comment by Aedif** [comment]
The module should already be doing this. I see that the focus works when pressing enter, but fails when selecting an image. I got a fix for it which will be included in the next release.

**Comment by Truncated** [comment]
> The module should already be doing this. I see that the focus works when pressing enter, but fails when selecting an image. I got a fix for it which will be included in the next release.

The cursor focus does not start in that field for me when the Select Variant window opens - I have to first click into the field at the end of the text manually to get the "Press Enter" thing to work.

I'll do a Find the culprit to see if something else is mingling with that selection / pull focus.

**Comment by Aedif** [comment]
Should be fixed as of releases 3.9.0 and 4.3.0
