### ISSUE TITLE
Enhancement - Default image improvements

### ISSUE THREAD

**Issue by Truncated** [Aedif/TokenVariants#87]
## Scenarios and Challenges:
1. Compendium objects only have one default when an image is not identified. Since the category of Items is so broad, a single icon leaves much to be desired.
2. There are a number of compendiums that have been made by the community or dedicated content creators that provide their own default icon for some sub-types (like weapons all having the same sword and armor all having the same shield), which is better than a bag icon, but unfortunately counts as having an image for the purposes of the Compendium Mapper.
3. Going through hundreds / thousands of anything one-at-a-time is rough, as is bulk-renaming assets and data cleansing in general. The less of any of these things that I need to do meticulously to make this stuff work, the better. Basically the goal is to make the squeeze effort < juice made. :)

To satisfy these challenges above, the following features would work in conjunction. They would really help polish up conpendiums and bridge the gap for users who do not have the time, capability, or resources to maintain large catalogues of correctly named images in having a consistant image set.

**Disclaimer**: I do not profess full expertise in all the things your module does still, nor Foundry as a whole, so I apologize in advance if something here is impossible, nonsense, or already exists. :)

### Default Icon settings
- Configuration settable globally with interface like Search Paths with the following columns:
  - Image Category (_drop-down from existing list_ + **All** [at top of list/default selection - skips Sub-Type if checked])
    - It's possible the All global default is just too much / complicated with the overall system to get involved in. Probably better to leave it as a drop-down with nothing defaulted, and rather give some method to make templates of configurations?
  - Sub-Type (_drop-down pull from world_ + **All** [at top of list/default selection])
  - Image Selection (file-picker)

**These settings could apply in distinct ways:**
1. To set the default image for new items of that Category/Sub-type made normally.
2. Allow the Compendium Mapper to use them in conjunction with "Only include entries with missing images" if Exact Match isn't found.
3. Allow the Compendium Mapper to use them in conjunction with "Only include entries with missing images" without matching being attempted.
4. Provide a selection method / button to "set to default" manually in the Select Variant dialogue box, if a setting exists.

### Compendium Mapper - Missing Mapper

- Configuration option within Compendium Mapper launch settings dialgue that modifies "Only include entries with missing images" to allow specified images to be treated as "missing" for the code. A few methods / modifiers to consider for this:
  - An interface like Search Paths that allow you to enter a list of images, where you add the images that are being used as "default" images manually in the compendium.
  - The ability to scan the compendium for the images already within the compendium, presenting you with a list of any that appear 2 or more times that you can accept and remove individuals as you like.
- Configuration option within Compendium Mapper launch settings dialgue that allows **Default Icon Settings** to be used for missing images, default set to _enabled_.
-------
Thank you for your consideration on all of these things, regardless of the outcome!

**Comment by Aedif** [comment]
Released **3.10.0** but this is likely to be the last feature release for v9

Takes too much work to keep both up to date, and latest 3.x versions aren't being updated to in large enough numbers to justify it.

**Comment by Truncated** [comment]
> Released **3.10.0** but this is likely to be the last feature release for v9
> 
> Takes too much work to keep both up to date, and latest 3.x versions aren't being downloaded in large enough numbers to justify it.

That's totally fair - I'm trying to switch to v10 as soon as I can.

**Comment by Aedif** [comment]
Implemented in releases 3.10.0 and 4.4.0
