### ISSUE TITLE
Enhancement - Empty Queue found in Compendium Mapper message

### ISSUE THREAD

**Issue by Truncated** [Aedif/TokenVariants#89]
When **Only include entries with missing images** is selected, but the compendium has a "default image" set that is not the same as the Foundry system "missing image", there will be no results. This is obviously to be expected... but can be misleading to a user.

In this case, the Select variant picker does not come up and there's no error generated (also as expected). 

Therefore, a message that your settings netted an Empty Queue would be beneficial to limit confusion when your users (or... umm... their friends?) are doing things at 2am and not thinking straight.

**Comment by Aedif** [comment]
A warning should now be displayed as of release [4.4.0](https://github.com/Aedif/TokenVariants/releases/tag/4.4.0)
