### ISSUE TITLE
Feature Request: Integrate with VTTA Tokenizer

### ISSUE THREAD

**Issue by JamzTheMan** [Aedif/TokenVariants#9]
If you wouldn't mind collaborating, I'd love to put a PR against https://github.com/VTTAssets/vtta-tokenizer to integrate your TokenVariants module (unless you wanted to do it)? Since Tokenizer already pops up on click of a portrait in the character sheet, It currently has 3 options/buttons that open images, either by "local computer", "web url", or "foundry folder". 

I would add a 4th button, if your module is detected, to open your search screen for a token selection? I would need a method that opened your search, (assuming passing creature name) and it would return back a selected image url?

Reason: My current workflow is 1 of 2,
1. If it's a creature from a compendium then I have only the "Portraits" available. I then use tokenizer to create the token using an overlay (I choose different overlays for different campaigns so I don't premake my token art for base creatures)
2. Prepping an AP/Module, I have custom creatures I need to create and I source in my own portraits, and usually also have the token art also created for these.

Today, having to select 1 of many different directories for my artwork, I love that your module will search and narrow it all down for me!

**Comment by Aedif** [comment]
Hi,

As of release 1.5.3 the method to display the popup should be exposed through **game**.TokenVariants.displayArtSelect

Notes here: https://github.com/Aedif/TokenVariants/releases/tag/1.5.3

Feel free to try it out.

Not sure if this is the best way of going about this so am open to suggestions if you think there is a more preferable one. :)

**Comment by JamzTheMan** [comment]
Awesome. I'll take a peek and see what I can come up with.

**Comment by JamzTheMan** [comment]
Oh well, nevermind, looks like @mrprimate beat me to it! Nice! :)
