### ISSUE TITLE
Compendium Mapper: Skip Entry or Open Filepicker

### ISSUE THREAD

**Issue by benbarbour** [Aedif/TokenVariants#90]
The ability to skip an entry and/or open a filepicker to choose a default svg or something would be really helpful in some instances

**Comment by Aedif** [comment]
You can skip an entry by closing the window (it will skip the entry and not clear the entire queue), pressing ESC, or pressing enter with the search bar focused.

 I'll consider adding some way of opening up the file picker from the Art Select window once I got some time.

**Comment by Aedif** [comment]
In additional to skip already being possible through a few means, as of verison [4.4.0](https://github.com/Aedif/TokenVariants/releases/tag/4.4.0) the Art Select window now also contains a new header button allowing to select an image using FilePicker
