### ISSUE TITLE
Actor Portrait don't Update

### ISSUE THREAD

**Issue by brunocalado** [Aedif/TokenVariants#94]
Hi.

I checked the option to update actor, but change the token art in token HUD don't update it.

![image](https://user-images.githubusercontent.com/4999783/200066492-c23f4259-873b-48a8-a319-b974016ac085.png)

![image](https://user-images.githubusercontent.com/4999783/200066325-ac31326f-5daa-4f73-b7a7-f49da43635d0.png)

**Comment by Aedif** [comment]
What TVA version are you on?

**Comment by Aedif** [comment]
Nevermind, the bug existed on both v9 and v10 version of the module. Jus tpushed out a new release, should be fixed now.

**Comment by brunocalado** [comment]
It's working now, but I can't make it greb the portrait.

https://user-images.githubusercontent.com/4999783/200092255-a83556c0-5f07-4d1c-92f1-deee53eea810.mp4


![image](https://user-images.githubusercontent.com/4999783/200092292-e4b17e6a-2dfd-41a8-aee3-ca02b7b334f0.png)

**Comment by Aedif** [comment]
For the 'Use a simialrly named file' feature to work you need to allow the module to somehow differentiate between token and portrait art.

This can be done in two ways; via filters or via image categories.

With the setup you showed above a filter like this should do the trick:

![image](https://user-images.githubusercontent.com/7693704/200094432-e798921b-7241-4c99-9e7c-c67749fe46ce.png)

Or placing portraits in a seperate folder and setting a search path with only the portrait category ticked:

![image](https://user-images.githubusercontent.com/7693704/200094477-a7be0e69-ab69-45fd-88c1-d08ddd8d3e2a.png)

**Comment by Aedif** [comment]
You sure you saved the filter before testing?

I just replicated your setup and it worked for me:


https://user-images.githubusercontent.com/7693704/200097740-d999940e-3620-40b9-922b-334a144d97cf.mp4

Mind exporting your settings and linking them to me?

I'll be going to bed now but I can help debug this more tomorrow.

**Comment by brunocalado** [comment]
Yes. I saved.
![image](https://user-images.githubusercontent.com/4999783/200124863-78450db0-8325-46b8-a681-80a8b877b481.png)

![image](https://user-images.githubusercontent.com/4999783/200124895-c9403a81-44f9-45fd-8a0f-f0d599a0703d.png)

[token-variants-settings.zip](https://github.com/Aedif/TokenVariants/files/9944016/token-variants-settings.zip)

**Comment by Aedif** [comment]
It works for me with your exact settings 😅 The only thing I can think of is that since you didn't include the search paths in the settings perhaps you've set the image categories on your path to not include the 'Portrait' category.

![image](https://user-images.githubusercontent.com/7693704/200129430-1c4264aa-7173-47b3-ab57-c242de772ed9.png)


I tested on v9 and v10, Dnd5e but the game system shouldn't make a difference.

**Comment by brunocalado** [comment]
> 

worked!
![image](https://user-images.githubusercontent.com/4999783/200136388-314ced6c-27e0-4447-a01c-169a4196d299.png)

tks
