### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Yuffyyy** [Aedif/TokenVariants#95]
Your new update game me an idea but it's probably a complicated one ! Would it be possible to have the same kind of automation but varying from one token to another ? Meaning we could have different token art varying with health condition they are !  Additionaly we could have the same kind of automation with incombat situation and out of combat situation. I would love to have my characters drawing and sheathing their weapons depending on wether they're fighting or not ♥

Anyway, love your module !

**Comment by Aedif** [comment]
It can already be set-up to vary from one token to another, or rather one Actor from another. Shift-Left clicking the status icon on the Token HUD will bring up a window where you configure effects for the Actor that that token represents. 

Pressing Shift+G or going to `Configure Settings > Active Effects > Global Effect Configurations` will bring up a window where you configure effects for ALL tokens.

You can also already setup images for when a token is in or out of combat:

https://github.com/Aedif/TokenVariants/releases/tag/1.29.2

Shift-Left click the 'Toggle Combat State' button in the Token HUD.

**Comment by Yuffyyy** [comment]
Oh ! I feel so silly ! I love it thank you very very very much !!
